#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : systemd
Version  : 242
Release  : 247
URL      : https://github.com/systemd/systemd/archive/v242.tar.gz
Source0  : https://github.com/systemd/systemd/archive/v242.tar.gz
Summary  : systemd Library
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: systemd-autostart = %{version}-%{release}
Requires: systemd-bin = %{version}-%{release}
Requires: systemd-config = %{version}-%{release}
Requires: systemd-data = %{version}-%{release}
Requires: systemd-lib = %{version}-%{release}
Requires: systemd-license = %{version}-%{release}
Requires: systemd-locales = %{version}-%{release}
Requires: systemd-man = %{version}-%{release}
Requires: systemd-services = %{version}-%{release}
Requires: libcap
BuildRequires : Linux-PAM-dev
BuildRequires : Linux-PAM-dev32
BuildRequires : acl-dev
BuildRequires : acl-dev32
BuildRequires : bash-completion-dev
BuildRequires : buildreq-meson
BuildRequires : cryptsetup-dev
BuildRequires : curl-dev
BuildRequires : dbus-dev
BuildRequires : dbus-dev32
BuildRequires : docbook-xml
BuildRequires : elfutils-dev
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : gettext-bin
BuildRequires : gettext-dev
BuildRequires : glib-bin
BuildRequires : glib-dev
BuildRequires : glib-dev32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : gnu-efi
BuildRequires : gnu-efi-dev
BuildRequires : gperf
BuildRequires : intltool
BuildRequires : intltool-dev
BuildRequires : iptables-dev
BuildRequires : iptables-dev32
BuildRequires : kbd
BuildRequires : kmod-dev
BuildRequires : kmod-dev32
BuildRequires : libcap
BuildRequires : libcap-dev
BuildRequires : libcap-dev32
BuildRequires : libcgroup-dev
BuildRequires : libffi-dev
BuildRequires : libgcrypt-dev
BuildRequires : libgcrypt-dev32
BuildRequires : libgpg-error-dev
BuildRequires : libmicrohttpd-dev
BuildRequires : libseccomp-dev
BuildRequires : libseccomp-dev32
BuildRequires : libxkbcommon-dev
BuildRequires : libxslt-bin
BuildRequires : openssl-dev
BuildRequires : pkg-config-dev
BuildRequires : pkgconfig(32xkbcommon)
BuildRequires : pkgconfig(audit)
BuildRequires : pkgconfig(bash-completion)
BuildRequires : pkgconfig(polkit-gobject-1)
BuildRequires : pkgconfig(xkbcommon)
BuildRequires : pkgconfig(zlib)
BuildRequires : polkit-dev
BuildRequires : python3
BuildRequires : readline-dev
BuildRequires : shadow
BuildRequires : util-linux-dev
BuildRequires : util-linux-dev32
BuildRequires : util-linux-extras
BuildRequires : xz-dev
BuildRequires : zlib-dev32
Patch1: 0001-Fix-preprocessor-issues-with-MS_MOVE-not-getting-def.patch
Patch2: 0002-journal-raise-compression-threshold.patch
Patch3: 0003-journal-clearout-drop-kmsg.patch
Patch4: 0004-core-use-mmap-to-load-files.patch
Patch5: 0005-Build-drop-pam-nsswitch-ship-legacy-tmpfiles.patch
Patch6: 0006-journal-flush-var-kmsg-after-starting.patch
Patch7: 0007-logind-pam-fix-systemd-user-to-include-common-sessio.patch
Patch8: 0008-analyze-increase-precision.patch
Patch9: 0009-sd-event-return-malloc-memory-reserves-when-main-loo.patch
Patch10: 0010-efi-boot-generator-Do-not-automount-boot-partition.patch
Patch11: 0011-core-do-not-apply-presets.patch
Patch12: 0012-locale-setup-set-default-locale-to-a-unicode-one.patch
Patch13: 0013-mount-setup-mount-kernel-fs-by-default.patch
Patch14: 0014-Ship-default-services-in-system-unit-dir.patch
Patch15: 0015-bootctl-Add-force-option-to-enable-chroot-install-re.patch
Patch16: 0016-kernel-install-Support-alternate-root-usage-via-SUBD.patch
Patch17: 0017-bootctl-Handle-gummiboot-systemd-migration.patch
Patch18: 0018-tmpfiles-Make-var-cache-ldconfig-world-readable.patch
Patch19: 0019-Set-a-default-unique-hostname-when-it-is-either-clr-.patch
Patch20: 0020-more-udev-children-workers.patch
Patch21: 0021-not-load-iptables.patch
Patch22: 0022-Add-journal-flush-service-for-Microsoft-Azure-VMs.patch
Patch23: 0023-Disable-resolved-as-default-resolver-write-at-boot.patch
Patch24: 0024-Enable-BBR-Bottleneck-Bandwidth-and-RTT.patch
Patch25: 0025-network-online-complete-once-one-link-is-online-not-.patch
Patch26: 0026-DHCP-retry-faster.patch
Patch27: 0027-Remove-libm-memory-overhead.patch
Patch28: 0028-udev-log-also-device-path.patch
Patch29: 0029-skip-not-present-ACPI-devices.patch
Patch30: 0030-Ensure-var-run-is-never-a-directory.patch
Patch31: 0031-Make-timesyncd-a-simple-service.patch
Patch32: 0032-Compile-udev-with-O3.patch
Patch33: 0033-Don-t-wait-for-utmp-at-shutdown.patch
Patch34: 0034-Don-t-do-transient-hostnames-we-set-ours-already.patch
Patch35: 0035-don-t-use-libm-just-for-integer-exp10.patch
Patch36: 0036-Notify-systemd-earlier-that-resolved-is-ready.patch
Patch37: 0037-Hand-off-coredumps-to-a-wrapper-that-will-optionally.patch
Patch38: 0038-add-stateless-for-locale-files-locale.conf-00-keyboa.patch
Patch39: 0039-Do-not-enable-audit-by-default-in-the-journal.patch
Patch40: 0040-Disable-XZ-support-in-the-journal.patch
Patch41: 0041-Localize-1-symbol.patch
Patch42: 0042-mount-setup-Harden-a-bit-the-options-for-certan-moun.patch
Patch43: 0043-Add-dependency-on-NetworkManager.patch
Patch44: 0044-network-remove-redunant-link-name-in-message.patch
Patch45: CVE-2018-20839.patch
Patch46: locale-archive.patch

%description
# systemd - System and Service Manager
<a href="https://in.waw.pl/systemd-github-state/systemd-systemd-issues.svg"><img align="right" src="https://in.waw.pl/systemd-github-state/systemd-systemd-issues-small.svg" alt="Count of open issues over time"></a>
<a href="https://in.waw.pl/systemd-github-state/systemd-systemd-pull-requests.svg"><img align="right" src="https://in.waw.pl/systemd-github-state/systemd-systemd-pull-requests-small.svg" alt="Count of open pull requests over time"></a>
[![Semaphore CI Build Status](https://semaphoreci.com/api/v1/projects/28a5a3ca-3c56-4078-8b5e-7ed6ef912e14/443470/shields_badge.svg)](https://semaphoreci.com/systemd/systemd)<br/>
[![Coverity Scan Status](https://scan.coverity.com/projects/350/badge.svg)](https://scan.coverity.com/projects/350)<br/>
[![CII Best Practices](https://bestpractices.coreinfrastructure.org/projects/1369/badge)](https://bestpractices.coreinfrastructure.org/projects/1369)<br/>
[![Travis CI Build Status](https://travis-ci.org/systemd/systemd.svg?branch=master)](https://travis-ci.org/systemd/systemd)<br/>
[![Language Grade: C/C++](https://img.shields.io/lgtm/grade/cpp/g/systemd/systemd.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/systemd/systemd/context:cpp)<br/>
[![CentOS CI Build Status](https://ci.centos.org/buildStatus/icon?job=systemd-pr-build)](https://ci.centos.org/job/systemd-pr-build/)

%package autostart
Summary: autostart components for the systemd package.
Group: Default

%description autostart
autostart components for the systemd package.


%package bin
Summary: bin components for the systemd package.
Group: Binaries
Requires: systemd-data = %{version}-%{release}
Requires: systemd-config = %{version}-%{release}
Requires: systemd-license = %{version}-%{release}
Requires: systemd-services = %{version}-%{release}

%description bin
bin components for the systemd package.


%package config
Summary: config components for the systemd package.
Group: Default

%description config
config components for the systemd package.


%package data
Summary: data components for the systemd package.
Group: Data

%description data
data components for the systemd package.


%package dev
Summary: dev components for the systemd package.
Group: Development
Requires: systemd-lib = %{version}-%{release}
Requires: systemd-bin = %{version}-%{release}
Requires: systemd-data = %{version}-%{release}
Provides: systemd-devel = %{version}-%{release}
Requires: systemd = %{version}-%{release}
Requires: systemd = %{version}-%{release}

%description dev
dev components for the systemd package.


%package dev32
Summary: dev32 components for the systemd package.
Group: Default
Requires: systemd-lib32 = %{version}-%{release}
Requires: systemd-bin = %{version}-%{release}
Requires: systemd-data = %{version}-%{release}
Requires: systemd-dev = %{version}-%{release}

%description dev32
dev32 components for the systemd package.


%package doc
Summary: doc components for the systemd package.
Group: Documentation
Requires: systemd-man = %{version}-%{release}

%description doc
doc components for the systemd package.


%package extras
Summary: extras components for the systemd package.
Group: Default

%description extras
extras components for the systemd package.


%package lib
Summary: lib components for the systemd package.
Group: Libraries
Requires: systemd-data = %{version}-%{release}
Requires: systemd-license = %{version}-%{release}

%description lib
lib components for the systemd package.


%package lib32
Summary: lib32 components for the systemd package.
Group: Default
Requires: systemd-data = %{version}-%{release}
Requires: systemd-license = %{version}-%{release}

%description lib32
lib32 components for the systemd package.


%package license
Summary: license components for the systemd package.
Group: Default

%description license
license components for the systemd package.


%package locales
Summary: locales components for the systemd package.
Group: Default

%description locales
locales components for the systemd package.


%package man
Summary: man components for the systemd package.
Group: Default

%description man
man components for the systemd package.


%package services
Summary: services components for the systemd package.
Group: Systemd services

%description services
services components for the systemd package.


%prep
%setup -q -n systemd-242
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1
%patch6 -p1
%patch7 -p1
%patch8 -p1
%patch9 -p1
%patch10 -p1
%patch11 -p1
%patch12 -p1
%patch13 -p1
%patch14 -p1
%patch15 -p1
%patch16 -p1
%patch17 -p1
%patch18 -p1
%patch19 -p1
%patch20 -p1
%patch21 -p1
%patch22 -p1
%patch23 -p1
%patch24 -p1
%patch25 -p1
%patch26 -p1
%patch27 -p1
%patch28 -p1
%patch29 -p1
%patch30 -p1
%patch31 -p1
%patch32 -p1
%patch33 -p1
%patch34 -p1
%patch35 -p1
%patch36 -p1
%patch37 -p1
%patch38 -p1
%patch39 -p1
%patch40 -p1
%patch41 -p1
%patch42 -p1
%patch43 -p1
%patch44 -p1
%patch45 -p1
%patch46 -p1
pushd ..
cp -a systemd-242 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1560707311
export CFLAGS="-O2 -g -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wformat -Wformat-security -Wno-error -Wl,-z,max-page-size=0x1000 -march=westmere -mtune=haswell"
export CXXFLAGS=$CFLAGS
unset LDFLAGS
export CFLAGS="$CFLAGS -fcf-protection=full -fno-lto -fstack-protector-strong "
export FCFLAGS="$CFLAGS -fcf-protection=full -fno-lto -fstack-protector-strong "
export FFLAGS="$CFLAGS -fcf-protection=full -fno-lto -fstack-protector-strong "
export CXXFLAGS="$CXXFLAGS -fcf-protection=full -fno-lto -fstack-protector-strong "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --prefix /usr --buildtype=plain -Ddefault-hierarchy=legacy \
-Dsmack=false \
-Dsysvinit-path= \
-Dsysvrcnd_path= \
-Dxz=true \
-Dgcrypt=true \
-Dlz4=false \
-Dqrencode=false \
-Dpcre2=false \
-Dlibidn=false \
-Dlibidn2=false \
-Ddefault-kill-user-processes=false \
-Dntp-servers="_gateway gateway 0.clearlinux.pool.ntp.org 1.clearlinux.pool.ntp.org 2.clearlinux.pool.ntp.org 3.clearlinux.pool.ntp.org time.intel.com" \
-Ddefault-dnssec=no  builddir
ninja -v -C builddir
pushd ../build32
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32"
meson --libdir=/usr/lib32 --prefix /usr --buildtype=plain -Ddefault-hierarchy=legacy \
-Dsmack=false \
-Dsysvinit-path= \
-Dsysvrcnd_path= \
-Dxz=true \
-Dgcrypt=true \
-Dlz4=false \
-Dqrencode=false \
-Dpcre2=false \
-Dlibidn=false \
-Dlibidn2=false \
-Ddefault-kill-user-processes=false \
-Dntp-servers="_gateway gateway 0.clearlinux.pool.ntp.org 1.clearlinux.pool.ntp.org 2.clearlinux.pool.ntp.org 3.clearlinux.pool.ntp.org time.intel.com" \
-Ddefault-dnssec=no -Dlibcryptsetup=false \
-Dgnutls=false \
-Dlibcurl=false \
-Delfutils=false \
-Dmicrohttpd=false \
-Dremote=false \
-Dxz=false \
-Dgcrypt=false \
-Dopenssl=false \
-Daudit=false builddir
ninja -v -C builddir
popd

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
ninja -C builddir test ||:

%install
mkdir -p %{buildroot}/usr/share/package-licenses/systemd
cp LICENSE.GPL2 %{buildroot}/usr/share/package-licenses/systemd/LICENSE.GPL2
cp LICENSE.LGPL2.1 %{buildroot}/usr/share/package-licenses/systemd/LICENSE.LGPL2.1
pushd ../build32
DESTDIR=%{buildroot} ninja -C builddir install
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang systemd
## install_append content
rm -f %{buildroot}/usr/lib/sysusers.d/basic.conf
rm -f %{buildroot}/usr/lib/sysusers.d/systemd.conf
rm -f %{buildroot}/usr/lib/sysusers.d/systemd-remote.conf
rmdir %{buildroot}/usr/lib/sysusers.d
rm -f %{buildroot}/usr/lib/systemd/libsystemd-shared.so
rm -f %{buildroot}/etc/systemd/journald.conf
rm -f %{buildroot}/etc/systemd/logind.conf
rm -f %{buildroot}/etc/systemd/resolved.conf
rm -f %{buildroot}/etc/systemd/system.conf
rm -f %{buildroot}/etc/systemd/timesyncd.conf
rm -f %{buildroot}/etc/systemd/user.conf
rm -f %{buildroot}/etc/udev/udev.conf
rmdir %{buildroot}/etc/udev/hwdb.d
rmdir %{buildroot}/etc/udev/rules.d
rmdir %{buildroot}/etc/udev
rm -f %{buildroot}/usr/lib/systemd/system/sysinit.target.wants/ldconfig.service
rm -f %{buildroot}/usr/lib/systemd/system/sysinit.target.wants/systemd-firstboot.service
rm -f %{buildroot}/usr/lib/systemd/system/sysinit.target.wants/systemd-hwdb-update.service
rm -f %{buildroot}/usr/lib/systemd/system/sysinit.target.wants/systemd-journal-catalog-update.service
rm -f %{buildroot}/usr/lib/systemd/system/sysinit.target.wants/systemd-sysusers.service
rm -f %{buildroot}/usr/lib/systemd/system/sysinit.target.wants/systemd-update-done.service
rm -f %{buildroot}/usr/lib/systemd/system/sysinit.target.wants/systemd-tmpfiles-setup-dev.service
rm -f %{buildroot}/usr/lib/systemd/system/sockets.target.wants/systemd-journald-audit.socket
rm -f %{buildroot}/etc/xdg/systemd/user
rm -f %{buildroot}/usr/lib/environment.d/99-environment.conf
mv %{buildroot}/etc/pam.d %{buildroot}/usr/share/.
mv %{buildroot}/usr/share/pkgconfig/* %{buildroot}/usr/lib64/pkgconfig/
rmdir %{buildroot}/usr/share/pkgconfig/
mkdir -p %{buildroot}/usr/lib/udev/hwdb.d/20
mv %{buildroot}/usr/lib/udev/hwdb.d/20-* %{buildroot}/usr/lib/udev/hwdb.d/20
builddir/udevadm hwdb --root %{buildroot} --update --usr
mv %{buildroot}/usr/lib/udev/hwdb.d/20/* %{buildroot}/usr/lib/udev/hwdb.d/
rmdir %{buildroot}/usr/lib/udev/hwdb.d/20
builddir/journalctl --root %{buildroot} --update-catalog
cp src/coredump/coredump-wrapper %{buildroot}/usr/lib/systemd/
rm -rvf %{buildroot}/usr/lib/kernel
rm -rvf %{buildroot}/var/lib/polkit-1
mkdir -p %{buildroot}/usr/share/clr-service-restart
ln -sf /usr/lib/systemd/system/systemd-timesyncd.service %{buildroot}/usr/share/clr-service-restart/systemd-timesyncd.service
ln -sf /usr/lib/systemd/system/systemd-resolved.service %{buildroot}/usr/share/clr-service-restart/systemd-resolved.service
ln -sf /usr/lib/systemd/system/systemd-udevd.service %{buildroot}/usr/share/clr-service-restart/systemd-udevd.service
ln -sf /usr/lib/systemd/system/systemd-journald.service %{buildroot}/usr/share/clr-service-restart/systemd-journald.service
mkdir -p %{buildroot}/usr/lib/systemd/sleep.conf.d/
cat <<EOF > %{buildroot}/usr/lib/systemd/sleep.conf.d/no-hibernate.conf
[Sleep]
AllowHibernation=no
EOF
## install_append end

%files
%defattr(-,root,root,-)
%exclude /usr/lib/rpm/macros.d/macros.systemd
%exclude /usr/lib/systemd/import-pubring.gpg
%exclude /usr/lib/systemd/system-generators/systemd-hibernate-resume-generator
%exclude /usr/lib/systemd/system-generators/systemd-system-update-generator
%exclude /usr/lib/systemd/system-generators/systemd-veritysetup-generator
%exclude /usr/lib/systemd/systemd-import
%exclude /usr/lib/systemd/systemd-importd
%exclude /usr/lib/systemd/systemd-journal-gatewayd
%exclude /usr/lib/systemd/systemd-journal-remote
%exclude /usr/lib/systemd/systemd-journal-upload
%exclude /usr/lib/systemd/systemd-pull
%exclude /usr/lib/systemd/systemd-update-done
%exclude /usr/lib/udev/cdrom_id
%exclude /usr/lib/udev/hwdb.d/20-OUI.hwdb
%exclude /usr/lib/udev/hwdb.d/20-acpi-vendor.hwdb
%exclude /usr/lib/udev/hwdb.d/20-bluetooth-vendor-product.hwdb
%exclude /usr/lib/udev/hwdb.d/20-net-ifname.hwdb
%exclude /usr/lib/udev/hwdb.d/20-pci-classes.hwdb
%exclude /usr/lib/udev/hwdb.d/20-pci-vendor-model.hwdb
%exclude /usr/lib/udev/hwdb.d/20-sdio-classes.hwdb
%exclude /usr/lib/udev/hwdb.d/20-sdio-vendor-model.hwdb
%exclude /usr/lib/udev/hwdb.d/20-usb-classes.hwdb
%exclude /usr/lib/udev/hwdb.d/60-evdev.hwdb
%exclude /usr/lib/udev/hwdb.d/60-keyboard.hwdb
%exclude /usr/lib/udev/hwdb.d/60-sensor.hwdb
%exclude /usr/lib/udev/hwdb.d/70-mouse.hwdb
%exclude /usr/lib/udev/hwdb.d/70-pointingstick.hwdb
%exclude /usr/lib/udev/hwdb.d/70-touchpad.hwdb
%exclude /usr/lib/udev/mtd_probe
%exclude /usr/lib/udev/v4l_id
%exclude /var/lib/systemd/catalog/database
/usr/lib/modprobe.d/systemd.conf
/usr/lib/systemd/boot/efi/linuxx64.efi.stub
/usr/lib/systemd/boot/efi/systemd-bootx64.efi
/usr/lib/systemd/catalog/systemd.be.catalog
/usr/lib/systemd/catalog/systemd.be@latin.catalog
/usr/lib/systemd/catalog/systemd.bg.catalog
/usr/lib/systemd/catalog/systemd.catalog
/usr/lib/systemd/catalog/systemd.de.catalog
/usr/lib/systemd/catalog/systemd.fr.catalog
/usr/lib/systemd/catalog/systemd.it.catalog
/usr/lib/systemd/catalog/systemd.pl.catalog
/usr/lib/systemd/catalog/systemd.pt_BR.catalog
/usr/lib/systemd/catalog/systemd.ru.catalog
/usr/lib/systemd/catalog/systemd.zh_CN.catalog
/usr/lib/systemd/catalog/systemd.zh_TW.catalog
/usr/lib/systemd/coredump-wrapper
/usr/lib/systemd/network/80-container-host0.network
/usr/lib/systemd/network/80-container-ve.network
/usr/lib/systemd/network/80-container-vz.network
/usr/lib/systemd/network/99-default.link
/usr/lib/systemd/portable/profile/default/service.conf
/usr/lib/systemd/portable/profile/nonetwork/service.conf
/usr/lib/systemd/portable/profile/strict/service.conf
/usr/lib/systemd/portable/profile/trusted/service.conf
/usr/lib/systemd/resolv.conf
/usr/lib/systemd/sleep.conf.d/no-hibernate.conf
/usr/lib/systemd/system-generators/systemd-bless-boot-generator
/usr/lib/systemd/system-generators/systemd-cryptsetup-generator
/usr/lib/systemd/system-generators/systemd-debug-generator
/usr/lib/systemd/system-generators/systemd-fstab-generator
/usr/lib/systemd/system-generators/systemd-getty-generator
/usr/lib/systemd/system-generators/systemd-gpt-auto-generator
/usr/lib/systemd/system-generators/systemd-run-generator
/usr/lib/systemd/system-preset/90-systemd.preset
/usr/lib/systemd/systemd
/usr/lib/systemd/systemd-ac-power
/usr/lib/systemd/systemd-backlight
/usr/lib/systemd/systemd-binfmt
/usr/lib/systemd/systemd-bless-boot
/usr/lib/systemd/systemd-boot-check-no-failures
/usr/lib/systemd/systemd-cgroups-agent
/usr/lib/systemd/systemd-coredump
/usr/lib/systemd/systemd-cryptsetup
/usr/lib/systemd/systemd-dissect
/usr/lib/systemd/systemd-export
/usr/lib/systemd/systemd-fsck
/usr/lib/systemd/systemd-growfs
/usr/lib/systemd/systemd-hibernate-resume
/usr/lib/systemd/systemd-hostnamed
/usr/lib/systemd/systemd-import-fs
/usr/lib/systemd/systemd-initctl
/usr/lib/systemd/systemd-journald
/usr/lib/systemd/systemd-localed
/usr/lib/systemd/systemd-logind
/usr/lib/systemd/systemd-machined
/usr/lib/systemd/systemd-makefs
/usr/lib/systemd/systemd-modules-load
/usr/lib/systemd/systemd-networkd
/usr/lib/systemd/systemd-networkd-wait-online
/usr/lib/systemd/systemd-portabled
/usr/lib/systemd/systemd-quotacheck
/usr/lib/systemd/systemd-random-seed
/usr/lib/systemd/systemd-remount-fs
/usr/lib/systemd/systemd-reply-password
/usr/lib/systemd/systemd-resolved
/usr/lib/systemd/systemd-rfkill
/usr/lib/systemd/systemd-shutdown
/usr/lib/systemd/systemd-sleep
/usr/lib/systemd/systemd-socket-proxyd
/usr/lib/systemd/systemd-sulogin-shell
/usr/lib/systemd/systemd-sysctl
/usr/lib/systemd/systemd-time-wait-sync
/usr/lib/systemd/systemd-timedated
/usr/lib/systemd/systemd-timesyncd
/usr/lib/systemd/systemd-udevd
/usr/lib/systemd/systemd-update-utmp
/usr/lib/systemd/systemd-user-runtime-dir
/usr/lib/systemd/systemd-user-sessions
/usr/lib/systemd/systemd-vconsole-setup
/usr/lib/systemd/systemd-veritysetup
/usr/lib/systemd/systemd-volatile-root
/usr/lib/systemd/user-environment-generators/30-systemd-environment-d-generator
/usr/lib/systemd/user-preset/90-systemd.preset
/usr/lib/udev/ata_id
/usr/lib/udev/hwdb.bin
/usr/lib/udev/hwdb.d/20-usb-vendor-model.hwdb
/usr/lib/udev/hwdb.d/20-vmbus-class.hwdb
/usr/lib/udev/hwdb.d/70-joystick.hwdb
/usr/lib/udev/scsi_id

%files autostart
%defattr(-,root,root,-)
/usr/lib/systemd/system/local-fs.target.wants/systemd-remount-fs.service
/usr/lib/systemd/system/local-fs.target.wants/tmp.mount
/usr/lib/systemd/system/machines.target.wants/var-lib-machines.mount
/usr/lib/systemd/system/multi-user.target.wants/getty.target
/usr/lib/systemd/system/multi-user.target.wants/remote-fs.target
/usr/lib/systemd/system/multi-user.target.wants/systemd-ask-password-wall.path
/usr/lib/systemd/system/multi-user.target.wants/systemd-logind.service
/usr/lib/systemd/system/multi-user.target.wants/systemd-networkd.service
/usr/lib/systemd/system/multi-user.target.wants/systemd-resolved.service
/usr/lib/systemd/system/multi-user.target.wants/systemd-user-sessions.service
/usr/lib/systemd/system/network-online.target.wants/systemd-networkd-wait-online.service
/usr/lib/systemd/system/remote-fs.target.wants/var-lib-machines.mount
/usr/lib/systemd/system/sockets.target.wants/systemd-coredump.socket
/usr/lib/systemd/system/sockets.target.wants/systemd-initctl.socket
/usr/lib/systemd/system/sockets.target.wants/systemd-journald-dev-log.socket
/usr/lib/systemd/system/sockets.target.wants/systemd-journald.socket
/usr/lib/systemd/system/sockets.target.wants/systemd-networkd.socket
/usr/lib/systemd/system/sockets.target.wants/systemd-udevd-control.socket
/usr/lib/systemd/system/sockets.target.wants/systemd-udevd-kernel.socket
/usr/lib/systemd/system/sysinit.target.wants/cryptsetup.target
/usr/lib/systemd/system/sysinit.target.wants/kmod-static-nodes.service
/usr/lib/systemd/system/sysinit.target.wants/proc-sys-fs-binfmt_misc.automount
/usr/lib/systemd/system/sysinit.target.wants/systemd-ask-password-console.path
/usr/lib/systemd/system/sysinit.target.wants/systemd-binfmt.service
/usr/lib/systemd/system/sysinit.target.wants/systemd-journal-flush-msft.service
/usr/lib/systemd/system/sysinit.target.wants/systemd-journal-flush.service
/usr/lib/systemd/system/sysinit.target.wants/systemd-journald.service
/usr/lib/systemd/system/sysinit.target.wants/systemd-machine-id-commit.service
/usr/lib/systemd/system/sysinit.target.wants/systemd-modules-load.service
/usr/lib/systemd/system/sysinit.target.wants/systemd-random-seed.service
/usr/lib/systemd/system/sysinit.target.wants/systemd-sysctl.service
/usr/lib/systemd/system/sysinit.target.wants/systemd-timesyncd.service
/usr/lib/systemd/system/sysinit.target.wants/systemd-tmpfiles-setup.service
/usr/lib/systemd/system/sysinit.target.wants/systemd-udev-trigger.service
/usr/lib/systemd/system/sysinit.target.wants/systemd-udevd.service
/usr/lib/systemd/system/sysinit.target.wants/systemd-update-utmp.service
/usr/lib/systemd/system/timers.target.wants/systemd-tmpfiles-clean.timer

%files bin
%defattr(-,root,root,-)
%exclude /usr/bin/kernel-install
%exclude /usr/bin/systemd-firstboot
%exclude /usr/bin/systemd-hwdb
%exclude /usr/bin/systemd-sysusers
/usr/bin/bootctl
/usr/bin/busctl
/usr/bin/coredumpctl
/usr/bin/halt
/usr/bin/hostnamectl
/usr/bin/init
/usr/bin/journalctl
/usr/bin/localectl
/usr/bin/loginctl
/usr/bin/machinectl
/usr/bin/networkctl
/usr/bin/portablectl
/usr/bin/poweroff
/usr/bin/reboot
/usr/bin/resolvconf
/usr/bin/resolvectl
/usr/bin/runlevel
/usr/bin/shutdown
/usr/bin/systemctl
/usr/bin/systemd-analyze
/usr/bin/systemd-ask-password
/usr/bin/systemd-cat
/usr/bin/systemd-cgls
/usr/bin/systemd-cgtop
/usr/bin/systemd-delta
/usr/bin/systemd-detect-virt
/usr/bin/systemd-escape
/usr/bin/systemd-id128
/usr/bin/systemd-inhibit
/usr/bin/systemd-machine-id-setup
/usr/bin/systemd-mount
/usr/bin/systemd-notify
/usr/bin/systemd-nspawn
/usr/bin/systemd-path
/usr/bin/systemd-resolve
/usr/bin/systemd-run
/usr/bin/systemd-socket-activate
/usr/bin/systemd-stdio-bridge
/usr/bin/systemd-tmpfiles
/usr/bin/systemd-tty-ask-password-agent
/usr/bin/systemd-umount
/usr/bin/telinit
/usr/bin/timedatectl
/usr/bin/udevadm

%files config
%defattr(-,root,root,-)
%exclude /usr/lib/udev/rules.d/60-cdrom_id.rules
%exclude /usr/lib/udev/rules.d/60-persistent-alsa.rules
%exclude /usr/lib/udev/rules.d/60-persistent-storage-tape.rules
%exclude /usr/lib/udev/rules.d/60-persistent-v4l.rules
%exclude /usr/lib/udev/rules.d/70-joystick.rules
%exclude /usr/lib/udev/rules.d/75-probe_mtd.rules
%exclude /usr/lib/udev/rules.d/78-sound-card.rules
/usr/lib/sysctl.d/50-coredump.conf
/usr/lib/sysctl.d/50-default.conf
/usr/lib/tmpfiles.d/etc.conf
/usr/lib/tmpfiles.d/home.conf
/usr/lib/tmpfiles.d/journal-nocow.conf
/usr/lib/tmpfiles.d/legacy.conf
/usr/lib/tmpfiles.d/portables.conf
/usr/lib/tmpfiles.d/systemd-nologin.conf
/usr/lib/tmpfiles.d/systemd-nspawn.conf
/usr/lib/tmpfiles.d/systemd.conf
/usr/lib/tmpfiles.d/tmp.conf
/usr/lib/tmpfiles.d/var.conf
/usr/lib/tmpfiles.d/x11.conf
/usr/lib/udev/rules.d/50-udev-default.rules
/usr/lib/udev/rules.d/60-block.rules
/usr/lib/udev/rules.d/60-drm.rules
/usr/lib/udev/rules.d/60-evdev.rules
/usr/lib/udev/rules.d/60-input-id.rules
/usr/lib/udev/rules.d/60-persistent-input.rules
/usr/lib/udev/rules.d/60-persistent-storage.rules
/usr/lib/udev/rules.d/60-sensor.rules
/usr/lib/udev/rules.d/60-serial.rules
/usr/lib/udev/rules.d/64-btrfs.rules
/usr/lib/udev/rules.d/70-mouse.rules
/usr/lib/udev/rules.d/70-power-switch.rules
/usr/lib/udev/rules.d/70-touchpad.rules
/usr/lib/udev/rules.d/70-uaccess.rules
/usr/lib/udev/rules.d/71-seat.rules
/usr/lib/udev/rules.d/73-seat-late.rules
/usr/lib/udev/rules.d/75-net-description.rules
/usr/lib/udev/rules.d/80-drivers.rules
/usr/lib/udev/rules.d/80-net-setup-link.rules
/usr/lib/udev/rules.d/90-vconsole.rules
/usr/lib/udev/rules.d/99-systemd.rules

%files data
%defattr(-,root,root,-)
%exclude /usr/share/bash-completion/completions/kernel-install
%exclude /usr/share/dbus-1/system-services/org.freedesktop.import1.service
%exclude /usr/share/dbus-1/system.d/org.freedesktop.import1.conf
%exclude /usr/share/polkit-1/actions/org.freedesktop.hostname1.policy
%exclude /usr/share/polkit-1/actions/org.freedesktop.import1.policy
%exclude /usr/share/polkit-1/actions/org.freedesktop.locale1.policy
%exclude /usr/share/polkit-1/actions/org.freedesktop.login1.policy
%exclude /usr/share/polkit-1/actions/org.freedesktop.machine1.policy
%exclude /usr/share/polkit-1/actions/org.freedesktop.systemd1.policy
%exclude /usr/share/polkit-1/actions/org.freedesktop.timedate1.policy
%exclude /usr/share/polkit-1/rules.d/systemd-networkd.rules
%exclude /usr/share/zsh/site-functions/_kernel-install
/usr/share/bash-completion/completions/bootctl
/usr/share/bash-completion/completions/busctl
/usr/share/bash-completion/completions/coredumpctl
/usr/share/bash-completion/completions/hostnamectl
/usr/share/bash-completion/completions/journalctl
/usr/share/bash-completion/completions/localectl
/usr/share/bash-completion/completions/loginctl
/usr/share/bash-completion/completions/machinectl
/usr/share/bash-completion/completions/networkctl
/usr/share/bash-completion/completions/portablectl
/usr/share/bash-completion/completions/resolvectl
/usr/share/bash-completion/completions/systemctl
/usr/share/bash-completion/completions/systemd-analyze
/usr/share/bash-completion/completions/systemd-cat
/usr/share/bash-completion/completions/systemd-cgls
/usr/share/bash-completion/completions/systemd-cgtop
/usr/share/bash-completion/completions/systemd-delta
/usr/share/bash-completion/completions/systemd-detect-virt
/usr/share/bash-completion/completions/systemd-nspawn
/usr/share/bash-completion/completions/systemd-path
/usr/share/bash-completion/completions/systemd-resolve
/usr/share/bash-completion/completions/systemd-run
/usr/share/bash-completion/completions/timedatectl
/usr/share/bash-completion/completions/udevadm
/usr/share/clr-service-restart/systemd-journald.service
/usr/share/clr-service-restart/systemd-resolved.service
/usr/share/clr-service-restart/systemd-timesyncd.service
/usr/share/clr-service-restart/systemd-udevd.service
/usr/share/dbus-1/services/org.freedesktop.systemd1.service
/usr/share/dbus-1/system-services/org.freedesktop.hostname1.service
/usr/share/dbus-1/system-services/org.freedesktop.locale1.service
/usr/share/dbus-1/system-services/org.freedesktop.login1.service
/usr/share/dbus-1/system-services/org.freedesktop.machine1.service
/usr/share/dbus-1/system-services/org.freedesktop.network1.service
/usr/share/dbus-1/system-services/org.freedesktop.portable1.service
/usr/share/dbus-1/system-services/org.freedesktop.resolve1.service
/usr/share/dbus-1/system-services/org.freedesktop.systemd1.service
/usr/share/dbus-1/system-services/org.freedesktop.timedate1.service
/usr/share/dbus-1/system-services/org.freedesktop.timesync1.service
/usr/share/dbus-1/system.d/org.freedesktop.hostname1.conf
/usr/share/dbus-1/system.d/org.freedesktop.locale1.conf
/usr/share/dbus-1/system.d/org.freedesktop.login1.conf
/usr/share/dbus-1/system.d/org.freedesktop.machine1.conf
/usr/share/dbus-1/system.d/org.freedesktop.network1.conf
/usr/share/dbus-1/system.d/org.freedesktop.portable1.conf
/usr/share/dbus-1/system.d/org.freedesktop.resolve1.conf
/usr/share/dbus-1/system.d/org.freedesktop.systemd1.conf
/usr/share/dbus-1/system.d/org.freedesktop.timedate1.conf
/usr/share/dbus-1/system.d/org.freedesktop.timesync1.conf
/usr/share/pam.d/systemd-user
/usr/share/polkit-1/actions/org.freedesktop.portable1.policy
/usr/share/polkit-1/actions/org.freedesktop.resolve1.policy
/usr/share/systemd/gatewayd/browse.html
/usr/share/systemd/kbd-model-map
/usr/share/systemd/language-fallback-map
/usr/share/zsh/site-functions/_bootctl
/usr/share/zsh/site-functions/_busctl
/usr/share/zsh/site-functions/_coredumpctl
/usr/share/zsh/site-functions/_hostnamectl
/usr/share/zsh/site-functions/_journalctl
/usr/share/zsh/site-functions/_localectl
/usr/share/zsh/site-functions/_loginctl
/usr/share/zsh/site-functions/_machinectl
/usr/share/zsh/site-functions/_networkctl
/usr/share/zsh/site-functions/_sd_hosts_or_user_at_host
/usr/share/zsh/site-functions/_sd_machines
/usr/share/zsh/site-functions/_sd_outputmodes
/usr/share/zsh/site-functions/_sd_unit_files
/usr/share/zsh/site-functions/_systemctl
/usr/share/zsh/site-functions/_systemd
/usr/share/zsh/site-functions/_systemd-analyze
/usr/share/zsh/site-functions/_systemd-delta
/usr/share/zsh/site-functions/_systemd-inhibit
/usr/share/zsh/site-functions/_systemd-nspawn
/usr/share/zsh/site-functions/_systemd-resolve
/usr/share/zsh/site-functions/_systemd-run
/usr/share/zsh/site-functions/_systemd-tmpfiles
/usr/share/zsh/site-functions/_timedatectl
/usr/share/zsh/site-functions/_udevadm

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/include/systemd/_sd-common.h
/usr/include/systemd/sd-bus-protocol.h
/usr/include/systemd/sd-bus-vtable.h
/usr/include/systemd/sd-bus.h
/usr/include/systemd/sd-daemon.h
/usr/include/systemd/sd-device.h
/usr/include/systemd/sd-event.h
/usr/include/systemd/sd-hwdb.h
/usr/include/systemd/sd-id128.h
/usr/include/systemd/sd-journal.h
/usr/include/systemd/sd-login.h
/usr/include/systemd/sd-messages.h
/usr/lib64/libsystemd.so
/usr/lib64/libudev.so
/usr/lib64/pkgconfig/libsystemd.pc
/usr/lib64/pkgconfig/libudev.pc
/usr/lib64/pkgconfig/systemd.pc
/usr/lib64/pkgconfig/udev.pc
/usr/share/man/man3/SD_ALERT.3
/usr/share/man/man3/SD_BUS_ERROR_ACCESS_DENIED.3
/usr/share/man/man3/SD_BUS_ERROR_ADDRESS_IN_USE.3
/usr/share/man/man3/SD_BUS_ERROR_AUTH_FAILED.3
/usr/share/man/man3/SD_BUS_ERROR_BAD_ADDRESS.3
/usr/share/man/man3/SD_BUS_ERROR_DISCONNECTED.3
/usr/share/man/man3/SD_BUS_ERROR_END.3
/usr/share/man/man3/SD_BUS_ERROR_FAILED.3
/usr/share/man/man3/SD_BUS_ERROR_FILE_EXISTS.3
/usr/share/man/man3/SD_BUS_ERROR_FILE_NOT_FOUND.3
/usr/share/man/man3/SD_BUS_ERROR_INCONSISTENT_MESSAGE.3
/usr/share/man/man3/SD_BUS_ERROR_INTERACTIVE_AUTHORIZATION_REQUIRED.3
/usr/share/man/man3/SD_BUS_ERROR_INVALID_ARGS.3
/usr/share/man/man3/SD_BUS_ERROR_INVALID_SIGNATURE.3
/usr/share/man/man3/SD_BUS_ERROR_IO_ERROR.3
/usr/share/man/man3/SD_BUS_ERROR_LIMITS_EXCEEDED.3
/usr/share/man/man3/SD_BUS_ERROR_MAKE_CONST.3
/usr/share/man/man3/SD_BUS_ERROR_MAP.3
/usr/share/man/man3/SD_BUS_ERROR_MATCH_RULE_INVALID.3
/usr/share/man/man3/SD_BUS_ERROR_MATCH_RULE_NOT_FOUND.3
/usr/share/man/man3/SD_BUS_ERROR_NAME_HAS_NO_OWNER.3
/usr/share/man/man3/SD_BUS_ERROR_NOT_SUPPORTED.3
/usr/share/man/man3/SD_BUS_ERROR_NO_MEMORY.3
/usr/share/man/man3/SD_BUS_ERROR_NO_NETWORK.3
/usr/share/man/man3/SD_BUS_ERROR_NO_REPLY.3
/usr/share/man/man3/SD_BUS_ERROR_NO_SERVER.3
/usr/share/man/man3/SD_BUS_ERROR_NULL.3
/usr/share/man/man3/SD_BUS_ERROR_PROPERTY_READ_ONLY.3
/usr/share/man/man3/SD_BUS_ERROR_SERVICE_UNKNOWN.3
/usr/share/man/man3/SD_BUS_ERROR_TIMEOUT.3
/usr/share/man/man3/SD_BUS_ERROR_UNIX_PROCESS_ID_UNKNOWN.3
/usr/share/man/man3/SD_BUS_ERROR_UNKNOWN_INTERFACE.3
/usr/share/man/man3/SD_BUS_ERROR_UNKNOWN_METHOD.3
/usr/share/man/man3/SD_BUS_ERROR_UNKNOWN_OBJECT.3
/usr/share/man/man3/SD_BUS_ERROR_UNKNOWN_PROPERTY.3
/usr/share/man/man3/SD_BUS_MESSAGE_METHOD_CALL.3
/usr/share/man/man3/SD_BUS_MESSAGE_METHOD_ERROR.3
/usr/share/man/man3/SD_BUS_MESSAGE_METHOD_RETURN.3
/usr/share/man/man3/SD_BUS_MESSAGE_SIGNAL.3
/usr/share/man/man3/SD_CRIT.3
/usr/share/man/man3/SD_DEBUG.3
/usr/share/man/man3/SD_EMERG.3
/usr/share/man/man3/SD_ERR.3
/usr/share/man/man3/SD_EVENT_ARMED.3
/usr/share/man/man3/SD_EVENT_EXITING.3
/usr/share/man/man3/SD_EVENT_FINISHED.3
/usr/share/man/man3/SD_EVENT_INITIAL.3
/usr/share/man/man3/SD_EVENT_OFF.3
/usr/share/man/man3/SD_EVENT_ON.3
/usr/share/man/man3/SD_EVENT_ONESHOT.3
/usr/share/man/man3/SD_EVENT_PENDING.3
/usr/share/man/man3/SD_EVENT_PREPARING.3
/usr/share/man/man3/SD_EVENT_PRIORITY_IDLE.3
/usr/share/man/man3/SD_EVENT_PRIORITY_IMPORTANT.3
/usr/share/man/man3/SD_EVENT_PRIORITY_NORMAL.3
/usr/share/man/man3/SD_EVENT_RUNNING.3
/usr/share/man/man3/SD_ID128_CONST_STR.3
/usr/share/man/man3/SD_ID128_FORMAT_STR.3
/usr/share/man/man3/SD_ID128_FORMAT_VAL.3
/usr/share/man/man3/SD_ID128_MAKE.3
/usr/share/man/man3/SD_ID128_MAKE_STR.3
/usr/share/man/man3/SD_ID128_NULL.3
/usr/share/man/man3/SD_INFO.3
/usr/share/man/man3/SD_JOURNAL_APPEND.3
/usr/share/man/man3/SD_JOURNAL_CURRENT_USER.3
/usr/share/man/man3/SD_JOURNAL_FOREACH.3
/usr/share/man/man3/SD_JOURNAL_FOREACH_BACKWARDS.3
/usr/share/man/man3/SD_JOURNAL_FOREACH_DATA.3
/usr/share/man/man3/SD_JOURNAL_FOREACH_FIELD.3
/usr/share/man/man3/SD_JOURNAL_FOREACH_UNIQUE.3
/usr/share/man/man3/SD_JOURNAL_INVALIDATE.3
/usr/share/man/man3/SD_JOURNAL_LOCAL_ONLY.3
/usr/share/man/man3/SD_JOURNAL_NOP.3
/usr/share/man/man3/SD_JOURNAL_OS_ROOT.3
/usr/share/man/man3/SD_JOURNAL_RUNTIME_ONLY.3
/usr/share/man/man3/SD_JOURNAL_SUPPRESS_LOCATION.3
/usr/share/man/man3/SD_JOURNAL_SYSTEM.3
/usr/share/man/man3/SD_LISTEN_FDS_START.3
/usr/share/man/man3/SD_NOTICE.3
/usr/share/man/man3/SD_WARNING.3
/usr/share/man/man3/libudev.3
/usr/share/man/man3/sd-bus-errors.3
/usr/share/man/man3/sd-bus.3
/usr/share/man/man3/sd-daemon.3
/usr/share/man/man3/sd-event.3
/usr/share/man/man3/sd-id128.3
/usr/share/man/man3/sd-journal.3
/usr/share/man/man3/sd-login.3
/usr/share/man/man3/sd_booted.3
/usr/share/man/man3/sd_bus_add_match.3
/usr/share/man/man3/sd_bus_add_match_async.3
/usr/share/man/man3/sd_bus_attach_event.3
/usr/share/man/man3/sd_bus_close.3
/usr/share/man/man3/sd_bus_close_unref.3
/usr/share/man/man3/sd_bus_close_unrefp.3
/usr/share/man/man3/sd_bus_creds_get_audit_login_uid.3
/usr/share/man/man3/sd_bus_creds_get_audit_session_id.3
/usr/share/man/man3/sd_bus_creds_get_augmented_mask.3
/usr/share/man/man3/sd_bus_creds_get_cgroup.3
/usr/share/man/man3/sd_bus_creds_get_cmdline.3
/usr/share/man/man3/sd_bus_creds_get_comm.3
/usr/share/man/man3/sd_bus_creds_get_description.3
/usr/share/man/man3/sd_bus_creds_get_egid.3
/usr/share/man/man3/sd_bus_creds_get_euid.3
/usr/share/man/man3/sd_bus_creds_get_exe.3
/usr/share/man/man3/sd_bus_creds_get_fsgid.3
/usr/share/man/man3/sd_bus_creds_get_fsuid.3
/usr/share/man/man3/sd_bus_creds_get_gid.3
/usr/share/man/man3/sd_bus_creds_get_mask.3
/usr/share/man/man3/sd_bus_creds_get_owner_uid.3
/usr/share/man/man3/sd_bus_creds_get_pid.3
/usr/share/man/man3/sd_bus_creds_get_ppid.3
/usr/share/man/man3/sd_bus_creds_get_selinux_context.3
/usr/share/man/man3/sd_bus_creds_get_session.3
/usr/share/man/man3/sd_bus_creds_get_sgid.3
/usr/share/man/man3/sd_bus_creds_get_slice.3
/usr/share/man/man3/sd_bus_creds_get_suid.3
/usr/share/man/man3/sd_bus_creds_get_supplementary_gids.3
/usr/share/man/man3/sd_bus_creds_get_tid.3
/usr/share/man/man3/sd_bus_creds_get_tid_comm.3
/usr/share/man/man3/sd_bus_creds_get_tty.3
/usr/share/man/man3/sd_bus_creds_get_uid.3
/usr/share/man/man3/sd_bus_creds_get_unique_name.3
/usr/share/man/man3/sd_bus_creds_get_unit.3
/usr/share/man/man3/sd_bus_creds_get_user_slice.3
/usr/share/man/man3/sd_bus_creds_get_user_unit.3
/usr/share/man/man3/sd_bus_creds_get_well_known_names.3
/usr/share/man/man3/sd_bus_creds_has_bounding_cap.3
/usr/share/man/man3/sd_bus_creds_has_effective_cap.3
/usr/share/man/man3/sd_bus_creds_has_inheritable_cap.3
/usr/share/man/man3/sd_bus_creds_has_permitted_cap.3
/usr/share/man/man3/sd_bus_creds_new_from_pid.3
/usr/share/man/man3/sd_bus_creds_ref.3
/usr/share/man/man3/sd_bus_creds_unref.3
/usr/share/man/man3/sd_bus_creds_unrefp.3
/usr/share/man/man3/sd_bus_default.3
/usr/share/man/man3/sd_bus_default_system.3
/usr/share/man/man3/sd_bus_default_user.3
/usr/share/man/man3/sd_bus_destroy_t.3
/usr/share/man/man3/sd_bus_detach_event.3
/usr/share/man/man3/sd_bus_error.3
/usr/share/man/man3/sd_bus_error_add_map.3
/usr/share/man/man3/sd_bus_error_copy.3
/usr/share/man/man3/sd_bus_error_free.3
/usr/share/man/man3/sd_bus_error_get_errno.3
/usr/share/man/man3/sd_bus_error_has_name.3
/usr/share/man/man3/sd_bus_error_is_set.3
/usr/share/man/man3/sd_bus_error_map.3
/usr/share/man/man3/sd_bus_error_move.3
/usr/share/man/man3/sd_bus_error_set.3
/usr/share/man/man3/sd_bus_error_set_const.3
/usr/share/man/man3/sd_bus_error_set_errno.3
/usr/share/man/man3/sd_bus_error_set_errnof.3
/usr/share/man/man3/sd_bus_error_set_errnofv.3
/usr/share/man/man3/sd_bus_error_setf.3
/usr/share/man/man3/sd_bus_flush.3
/usr/share/man/man3/sd_bus_flush_close_unref.3
/usr/share/man/man3/sd_bus_flush_close_unrefp.3
/usr/share/man/man3/sd_bus_get_allow_interactive_authorization.3
/usr/share/man/man3/sd_bus_get_close_on_exit.3
/usr/share/man/man3/sd_bus_get_connected_signal.3
/usr/share/man/man3/sd_bus_get_description.3
/usr/share/man/man3/sd_bus_get_event.3
/usr/share/man/man3/sd_bus_get_events.3
/usr/share/man/man3/sd_bus_get_fd.3
/usr/share/man/man3/sd_bus_get_n_queued_read.3
/usr/share/man/man3/sd_bus_get_n_queued_write.3
/usr/share/man/man3/sd_bus_get_sender.3
/usr/share/man/man3/sd_bus_get_timeout.3
/usr/share/man/man3/sd_bus_get_watch_bind.3
/usr/share/man/man3/sd_bus_is_open.3
/usr/share/man/man3/sd_bus_is_ready.3
/usr/share/man/man3/sd_bus_match_signal.3
/usr/share/man/man3/sd_bus_match_signal_async.3
/usr/share/man/man3/sd_bus_message_append.3
/usr/share/man/man3/sd_bus_message_append_array.3
/usr/share/man/man3/sd_bus_message_append_array_iovec.3
/usr/share/man/man3/sd_bus_message_append_array_memfd.3
/usr/share/man/man3/sd_bus_message_append_array_space.3
/usr/share/man/man3/sd_bus_message_append_basic.3
/usr/share/man/man3/sd_bus_message_append_string_iovec.3
/usr/share/man/man3/sd_bus_message_append_string_memfd.3
/usr/share/man/man3/sd_bus_message_append_string_space.3
/usr/share/man/man3/sd_bus_message_append_strv.3
/usr/share/man/man3/sd_bus_message_appendv.3
/usr/share/man/man3/sd_bus_message_copy.3
/usr/share/man/man3/sd_bus_message_get_auto_start.3
/usr/share/man/man3/sd_bus_message_get_bus.3
/usr/share/man/man3/sd_bus_message_get_cookie.3
/usr/share/man/man3/sd_bus_message_get_destination.3
/usr/share/man/man3/sd_bus_message_get_expect_reply.3
/usr/share/man/man3/sd_bus_message_get_interface.3
/usr/share/man/man3/sd_bus_message_get_member.3
/usr/share/man/man3/sd_bus_message_get_monotonic_usec.3
/usr/share/man/man3/sd_bus_message_get_path.3
/usr/share/man/man3/sd_bus_message_get_realtime_usec.3
/usr/share/man/man3/sd_bus_message_get_reply_cookie.3
/usr/share/man/man3/sd_bus_message_get_sender.3
/usr/share/man/man3/sd_bus_message_get_seqnum.3
/usr/share/man/man3/sd_bus_message_get_signature.3
/usr/share/man/man3/sd_bus_message_get_type.3
/usr/share/man/man3/sd_bus_message_has_signature.3
/usr/share/man/man3/sd_bus_message_is_empty.3
/usr/share/man/man3/sd_bus_message_is_method_call.3
/usr/share/man/man3/sd_bus_message_is_method_error.3
/usr/share/man/man3/sd_bus_message_is_signal.3
/usr/share/man/man3/sd_bus_message_new.3
/usr/share/man/man3/sd_bus_message_new_method_call.3
/usr/share/man/man3/sd_bus_message_new_method_errno.3
/usr/share/man/man3/sd_bus_message_new_method_errnof.3
/usr/share/man/man3/sd_bus_message_new_method_error.3
/usr/share/man/man3/sd_bus_message_new_method_errorf.3
/usr/share/man/man3/sd_bus_message_new_method_return.3
/usr/share/man/man3/sd_bus_message_new_signal.3
/usr/share/man/man3/sd_bus_message_read.3
/usr/share/man/man3/sd_bus_message_read_array.3
/usr/share/man/man3/sd_bus_message_read_basic.3
/usr/share/man/man3/sd_bus_message_readv.3
/usr/share/man/man3/sd_bus_message_ref.3
/usr/share/man/man3/sd_bus_message_rewind.3
/usr/share/man/man3/sd_bus_message_set_auto_start.3
/usr/share/man/man3/sd_bus_message_set_destination.3
/usr/share/man/man3/sd_bus_message_set_expect_reply.3
/usr/share/man/man3/sd_bus_message_set_sender.3
/usr/share/man/man3/sd_bus_message_skip.3
/usr/share/man/man3/sd_bus_message_unref.3
/usr/share/man/man3/sd_bus_message_unrefp.3
/usr/share/man/man3/sd_bus_message_verify_type.3
/usr/share/man/man3/sd_bus_negotiate_creds.3
/usr/share/man/man3/sd_bus_negotiate_fds.3
/usr/share/man/man3/sd_bus_negotiate_timestamp.3
/usr/share/man/man3/sd_bus_new.3
/usr/share/man/man3/sd_bus_open.3
/usr/share/man/man3/sd_bus_open_system.3
/usr/share/man/man3/sd_bus_open_system_machine.3
/usr/share/man/man3/sd_bus_open_system_remote.3
/usr/share/man/man3/sd_bus_open_system_with_description.3
/usr/share/man/man3/sd_bus_open_user.3
/usr/share/man/man3/sd_bus_open_user_with_description.3
/usr/share/man/man3/sd_bus_open_with_description.3
/usr/share/man/man3/sd_bus_path_decode.3
/usr/share/man/man3/sd_bus_path_decode_many.3
/usr/share/man/man3/sd_bus_path_encode.3
/usr/share/man/man3/sd_bus_path_encode_many.3
/usr/share/man/man3/sd_bus_process.3
/usr/share/man/man3/sd_bus_ref.3
/usr/share/man/man3/sd_bus_release_name.3
/usr/share/man/man3/sd_bus_release_name_async.3
/usr/share/man/man3/sd_bus_reply_method_errno.3
/usr/share/man/man3/sd_bus_reply_method_errnof.3
/usr/share/man/man3/sd_bus_reply_method_error.3
/usr/share/man/man3/sd_bus_reply_method_errorf.3
/usr/share/man/man3/sd_bus_request_name.3
/usr/share/man/man3/sd_bus_request_name_async.3
/usr/share/man/man3/sd_bus_set_allow_interactive_authorization.3
/usr/share/man/man3/sd_bus_set_anonymous.3
/usr/share/man/man3/sd_bus_set_close_on_exit.3
/usr/share/man/man3/sd_bus_set_connected_signal.3
/usr/share/man/man3/sd_bus_set_description.3
/usr/share/man/man3/sd_bus_set_sender.3
/usr/share/man/man3/sd_bus_set_trusted.3
/usr/share/man/man3/sd_bus_set_watch_bind.3
/usr/share/man/man3/sd_bus_slot_get_bus.3
/usr/share/man/man3/sd_bus_slot_get_description.3
/usr/share/man/man3/sd_bus_slot_get_destroy_callback.3
/usr/share/man/man3/sd_bus_slot_get_floating.3
/usr/share/man/man3/sd_bus_slot_get_userdata.3
/usr/share/man/man3/sd_bus_slot_ref.3
/usr/share/man/man3/sd_bus_slot_set_description.3
/usr/share/man/man3/sd_bus_slot_set_destroy_callback.3
/usr/share/man/man3/sd_bus_slot_set_floating.3
/usr/share/man/man3/sd_bus_slot_set_userdata.3
/usr/share/man/man3/sd_bus_slot_unref.3
/usr/share/man/man3/sd_bus_slot_unrefp.3
/usr/share/man/man3/sd_bus_track_add_name.3
/usr/share/man/man3/sd_bus_track_add_sender.3
/usr/share/man/man3/sd_bus_track_contains.3
/usr/share/man/man3/sd_bus_track_count.3
/usr/share/man/man3/sd_bus_track_count_name.3
/usr/share/man/man3/sd_bus_track_count_sender.3
/usr/share/man/man3/sd_bus_track_first.3
/usr/share/man/man3/sd_bus_track_get_bus.3
/usr/share/man/man3/sd_bus_track_get_destroy_callback.3
/usr/share/man/man3/sd_bus_track_get_recursive.3
/usr/share/man/man3/sd_bus_track_get_userdata.3
/usr/share/man/man3/sd_bus_track_new.3
/usr/share/man/man3/sd_bus_track_next.3
/usr/share/man/man3/sd_bus_track_ref.3
/usr/share/man/man3/sd_bus_track_remove_name.3
/usr/share/man/man3/sd_bus_track_remove_sender.3
/usr/share/man/man3/sd_bus_track_set_destroy_callback.3
/usr/share/man/man3/sd_bus_track_set_recursive.3
/usr/share/man/man3/sd_bus_track_set_userdata.3
/usr/share/man/man3/sd_bus_track_unref.3
/usr/share/man/man3/sd_bus_track_unrefp.3
/usr/share/man/man3/sd_bus_unref.3
/usr/share/man/man3/sd_bus_unrefp.3
/usr/share/man/man3/sd_bus_wait.3
/usr/share/man/man3/sd_event.3
/usr/share/man/man3/sd_event_add_child.3
/usr/share/man/man3/sd_event_add_defer.3
/usr/share/man/man3/sd_event_add_exit.3
/usr/share/man/man3/sd_event_add_inotify.3
/usr/share/man/man3/sd_event_add_io.3
/usr/share/man/man3/sd_event_add_post.3
/usr/share/man/man3/sd_event_add_signal.3
/usr/share/man/man3/sd_event_add_time.3
/usr/share/man/man3/sd_event_child_handler_t.3
/usr/share/man/man3/sd_event_default.3
/usr/share/man/man3/sd_event_destroy_t.3
/usr/share/man/man3/sd_event_dispatch.3
/usr/share/man/man3/sd_event_exit.3
/usr/share/man/man3/sd_event_get_exit_code.3
/usr/share/man/man3/sd_event_get_fd.3
/usr/share/man/man3/sd_event_get_iteration.3
/usr/share/man/man3/sd_event_get_state.3
/usr/share/man/man3/sd_event_get_tid.3
/usr/share/man/man3/sd_event_get_watchdog.3
/usr/share/man/man3/sd_event_handler_t.3
/usr/share/man/man3/sd_event_inotify_handler_t.3
/usr/share/man/man3/sd_event_io_handler_t.3
/usr/share/man/man3/sd_event_loop.3
/usr/share/man/man3/sd_event_new.3
/usr/share/man/man3/sd_event_now.3
/usr/share/man/man3/sd_event_prepare.3
/usr/share/man/man3/sd_event_ref.3
/usr/share/man/man3/sd_event_run.3
/usr/share/man/man3/sd_event_set_watchdog.3
/usr/share/man/man3/sd_event_signal_handler_t.3
/usr/share/man/man3/sd_event_source.3
/usr/share/man/man3/sd_event_source_get_child_pid.3
/usr/share/man/man3/sd_event_source_get_description.3
/usr/share/man/man3/sd_event_source_get_destroy_callback.3
/usr/share/man/man3/sd_event_source_get_enabled.3
/usr/share/man/man3/sd_event_source_get_event.3
/usr/share/man/man3/sd_event_source_get_inotify_mask.3
/usr/share/man/man3/sd_event_source_get_io_events.3
/usr/share/man/man3/sd_event_source_get_io_fd.3
/usr/share/man/man3/sd_event_source_get_io_fd_own.3
/usr/share/man/man3/sd_event_source_get_io_revents.3
/usr/share/man/man3/sd_event_source_get_pending.3
/usr/share/man/man3/sd_event_source_get_priority.3
/usr/share/man/man3/sd_event_source_get_signal.3
/usr/share/man/man3/sd_event_source_get_time.3
/usr/share/man/man3/sd_event_source_get_time_accuracy.3
/usr/share/man/man3/sd_event_source_get_time_clock.3
/usr/share/man/man3/sd_event_source_get_userdata.3
/usr/share/man/man3/sd_event_source_ref.3
/usr/share/man/man3/sd_event_source_set_description.3
/usr/share/man/man3/sd_event_source_set_destroy_callback.3
/usr/share/man/man3/sd_event_source_set_enabled.3
/usr/share/man/man3/sd_event_source_set_io_events.3
/usr/share/man/man3/sd_event_source_set_io_fd.3
/usr/share/man/man3/sd_event_source_set_io_fd_own.3
/usr/share/man/man3/sd_event_source_set_prepare.3
/usr/share/man/man3/sd_event_source_set_priority.3
/usr/share/man/man3/sd_event_source_set_time.3
/usr/share/man/man3/sd_event_source_set_time_accuracy.3
/usr/share/man/man3/sd_event_source_set_userdata.3
/usr/share/man/man3/sd_event_source_unref.3
/usr/share/man/man3/sd_event_source_unrefp.3
/usr/share/man/man3/sd_event_time_handler_t.3
/usr/share/man/man3/sd_event_unref.3
/usr/share/man/man3/sd_event_unrefp.3
/usr/share/man/man3/sd_event_wait.3
/usr/share/man/man3/sd_get_machine_names.3
/usr/share/man/man3/sd_get_seats.3
/usr/share/man/man3/sd_get_sessions.3
/usr/share/man/man3/sd_get_uids.3
/usr/share/man/man3/sd_id128_equal.3
/usr/share/man/man3/sd_id128_from_string.3
/usr/share/man/man3/sd_id128_get_boot.3
/usr/share/man/man3/sd_id128_get_boot_app_specific.3
/usr/share/man/man3/sd_id128_get_invocation.3
/usr/share/man/man3/sd_id128_get_machine.3
/usr/share/man/man3/sd_id128_get_machine_app_specific.3
/usr/share/man/man3/sd_id128_is_null.3
/usr/share/man/man3/sd_id128_randomize.3
/usr/share/man/man3/sd_id128_t.3
/usr/share/man/man3/sd_id128_to_string.3
/usr/share/man/man3/sd_is_fifo.3
/usr/share/man/man3/sd_is_mq.3
/usr/share/man/man3/sd_is_socket.3
/usr/share/man/man3/sd_is_socket_inet.3
/usr/share/man/man3/sd_is_socket_sockaddr.3
/usr/share/man/man3/sd_is_socket_unix.3
/usr/share/man/man3/sd_is_special.3
/usr/share/man/man3/sd_journal.3
/usr/share/man/man3/sd_journal_add_conjunction.3
/usr/share/man/man3/sd_journal_add_disjunction.3
/usr/share/man/man3/sd_journal_add_match.3
/usr/share/man/man3/sd_journal_close.3
/usr/share/man/man3/sd_journal_enumerate_data.3
/usr/share/man/man3/sd_journal_enumerate_fields.3
/usr/share/man/man3/sd_journal_enumerate_unique.3
/usr/share/man/man3/sd_journal_flush_matches.3
/usr/share/man/man3/sd_journal_get_catalog.3
/usr/share/man/man3/sd_journal_get_catalog_for_message_id.3
/usr/share/man/man3/sd_journal_get_cursor.3
/usr/share/man/man3/sd_journal_get_cutoff_monotonic_usec.3
/usr/share/man/man3/sd_journal_get_cutoff_realtime_usec.3
/usr/share/man/man3/sd_journal_get_data.3
/usr/share/man/man3/sd_journal_get_data_threshold.3
/usr/share/man/man3/sd_journal_get_events.3
/usr/share/man/man3/sd_journal_get_fd.3
/usr/share/man/man3/sd_journal_get_monotonic_usec.3
/usr/share/man/man3/sd_journal_get_realtime_usec.3
/usr/share/man/man3/sd_journal_get_timeout.3
/usr/share/man/man3/sd_journal_get_usage.3
/usr/share/man/man3/sd_journal_has_persistent_files.3
/usr/share/man/man3/sd_journal_has_runtime_files.3
/usr/share/man/man3/sd_journal_next.3
/usr/share/man/man3/sd_journal_next_skip.3
/usr/share/man/man3/sd_journal_open.3
/usr/share/man/man3/sd_journal_open_directory.3
/usr/share/man/man3/sd_journal_open_directory_fd.3
/usr/share/man/man3/sd_journal_open_files.3
/usr/share/man/man3/sd_journal_open_files_fd.3
/usr/share/man/man3/sd_journal_perror.3
/usr/share/man/man3/sd_journal_previous.3
/usr/share/man/man3/sd_journal_previous_skip.3
/usr/share/man/man3/sd_journal_print.3
/usr/share/man/man3/sd_journal_printv.3
/usr/share/man/man3/sd_journal_process.3
/usr/share/man/man3/sd_journal_query_unique.3
/usr/share/man/man3/sd_journal_reliable_fd.3
/usr/share/man/man3/sd_journal_restart_data.3
/usr/share/man/man3/sd_journal_restart_fields.3
/usr/share/man/man3/sd_journal_restart_unique.3
/usr/share/man/man3/sd_journal_seek_cursor.3
/usr/share/man/man3/sd_journal_seek_head.3
/usr/share/man/man3/sd_journal_seek_monotonic_usec.3
/usr/share/man/man3/sd_journal_seek_realtime_usec.3
/usr/share/man/man3/sd_journal_seek_tail.3
/usr/share/man/man3/sd_journal_send.3
/usr/share/man/man3/sd_journal_sendv.3
/usr/share/man/man3/sd_journal_set_data_threshold.3
/usr/share/man/man3/sd_journal_stream_fd.3
/usr/share/man/man3/sd_journal_test_cursor.3
/usr/share/man/man3/sd_journal_wait.3
/usr/share/man/man3/sd_listen_fds.3
/usr/share/man/man3/sd_listen_fds_with_names.3
/usr/share/man/man3/sd_login_monitor.3
/usr/share/man/man3/sd_login_monitor_flush.3
/usr/share/man/man3/sd_login_monitor_get_events.3
/usr/share/man/man3/sd_login_monitor_get_fd.3
/usr/share/man/man3/sd_login_monitor_get_timeout.3
/usr/share/man/man3/sd_login_monitor_new.3
/usr/share/man/man3/sd_login_monitor_unref.3
/usr/share/man/man3/sd_login_monitor_unrefp.3
/usr/share/man/man3/sd_machine_get_class.3
/usr/share/man/man3/sd_machine_get_ifindices.3
/usr/share/man/man3/sd_notify.3
/usr/share/man/man3/sd_notifyf.3
/usr/share/man/man3/sd_peer_get_cgroup.3
/usr/share/man/man3/sd_peer_get_machine_name.3
/usr/share/man/man3/sd_peer_get_owner_uid.3
/usr/share/man/man3/sd_peer_get_session.3
/usr/share/man/man3/sd_peer_get_slice.3
/usr/share/man/man3/sd_peer_get_unit.3
/usr/share/man/man3/sd_peer_get_user_slice.3
/usr/share/man/man3/sd_peer_get_user_unit.3
/usr/share/man/man3/sd_pid_get_cgroup.3
/usr/share/man/man3/sd_pid_get_machine_name.3
/usr/share/man/man3/sd_pid_get_owner_uid.3
/usr/share/man/man3/sd_pid_get_session.3
/usr/share/man/man3/sd_pid_get_slice.3
/usr/share/man/man3/sd_pid_get_unit.3
/usr/share/man/man3/sd_pid_get_user_slice.3
/usr/share/man/man3/sd_pid_get_user_unit.3
/usr/share/man/man3/sd_pid_notify.3
/usr/share/man/man3/sd_pid_notify_with_fds.3
/usr/share/man/man3/sd_pid_notifyf.3
/usr/share/man/man3/sd_seat_can_graphical.3
/usr/share/man/man3/sd_seat_can_multi_session.3
/usr/share/man/man3/sd_seat_can_tty.3
/usr/share/man/man3/sd_seat_get_active.3
/usr/share/man/man3/sd_seat_get_sessions.3
/usr/share/man/man3/sd_session_get_class.3
/usr/share/man/man3/sd_session_get_desktop.3
/usr/share/man/man3/sd_session_get_display.3
/usr/share/man/man3/sd_session_get_remote_host.3
/usr/share/man/man3/sd_session_get_remote_user.3
/usr/share/man/man3/sd_session_get_seat.3
/usr/share/man/man3/sd_session_get_service.3
/usr/share/man/man3/sd_session_get_state.3
/usr/share/man/man3/sd_session_get_tty.3
/usr/share/man/man3/sd_session_get_type.3
/usr/share/man/man3/sd_session_get_uid.3
/usr/share/man/man3/sd_session_get_vt.3
/usr/share/man/man3/sd_session_is_active.3
/usr/share/man/man3/sd_session_is_remote.3
/usr/share/man/man3/sd_uid_get_display.3
/usr/share/man/man3/sd_uid_get_seats.3
/usr/share/man/man3/sd_uid_get_sessions.3
/usr/share/man/man3/sd_uid_get_state.3
/usr/share/man/man3/sd_uid_is_on_seat.3
/usr/share/man/man3/sd_watchdog_enabled.3
/usr/share/man/man3/udev_device_get_action.3
/usr/share/man/man3/udev_device_get_devlinks_list_entry.3
/usr/share/man/man3/udev_device_get_devnode.3
/usr/share/man/man3/udev_device_get_devnum.3
/usr/share/man/man3/udev_device_get_devpath.3
/usr/share/man/man3/udev_device_get_devtype.3
/usr/share/man/man3/udev_device_get_driver.3
/usr/share/man/man3/udev_device_get_is_initialized.3
/usr/share/man/man3/udev_device_get_parent.3
/usr/share/man/man3/udev_device_get_parent_with_subsystem_devtype.3
/usr/share/man/man3/udev_device_get_properties_list_entry.3
/usr/share/man/man3/udev_device_get_property_value.3
/usr/share/man/man3/udev_device_get_subsystem.3
/usr/share/man/man3/udev_device_get_sysattr_list_entry.3
/usr/share/man/man3/udev_device_get_sysattr_value.3
/usr/share/man/man3/udev_device_get_sysname.3
/usr/share/man/man3/udev_device_get_sysnum.3
/usr/share/man/man3/udev_device_get_syspath.3
/usr/share/man/man3/udev_device_get_tags_list_entry.3
/usr/share/man/man3/udev_device_get_udev.3
/usr/share/man/man3/udev_device_has_tag.3
/usr/share/man/man3/udev_device_new_from_device_id.3
/usr/share/man/man3/udev_device_new_from_devnum.3
/usr/share/man/man3/udev_device_new_from_environment.3
/usr/share/man/man3/udev_device_new_from_subsystem_sysname.3
/usr/share/man/man3/udev_device_new_from_syspath.3
/usr/share/man/man3/udev_device_ref.3
/usr/share/man/man3/udev_device_set_sysattr_value.3
/usr/share/man/man3/udev_device_unref.3
/usr/share/man/man3/udev_enumerate_add_match_is_initialized.3
/usr/share/man/man3/udev_enumerate_add_match_parent.3
/usr/share/man/man3/udev_enumerate_add_match_property.3
/usr/share/man/man3/udev_enumerate_add_match_subsystem.3
/usr/share/man/man3/udev_enumerate_add_match_sysattr.3
/usr/share/man/man3/udev_enumerate_add_match_sysname.3
/usr/share/man/man3/udev_enumerate_add_match_tag.3
/usr/share/man/man3/udev_enumerate_add_nomatch_subsystem.3
/usr/share/man/man3/udev_enumerate_add_nomatch_sysattr.3
/usr/share/man/man3/udev_enumerate_add_syspath.3
/usr/share/man/man3/udev_enumerate_get_list_entry.3
/usr/share/man/man3/udev_enumerate_get_udev.3
/usr/share/man/man3/udev_enumerate_new.3
/usr/share/man/man3/udev_enumerate_ref.3
/usr/share/man/man3/udev_enumerate_scan_devices.3
/usr/share/man/man3/udev_enumerate_scan_subsystems.3
/usr/share/man/man3/udev_enumerate_unref.3
/usr/share/man/man3/udev_list_entry.3
/usr/share/man/man3/udev_list_entry_get_by_name.3
/usr/share/man/man3/udev_list_entry_get_name.3
/usr/share/man/man3/udev_list_entry_get_next.3
/usr/share/man/man3/udev_list_entry_get_value.3
/usr/share/man/man3/udev_monitor_enable_receiving.3
/usr/share/man/man3/udev_monitor_filter_add_match_subsystem_devtype.3
/usr/share/man/man3/udev_monitor_filter_add_match_tag.3
/usr/share/man/man3/udev_monitor_filter_remove.3
/usr/share/man/man3/udev_monitor_filter_update.3
/usr/share/man/man3/udev_monitor_get_fd.3
/usr/share/man/man3/udev_monitor_get_udev.3
/usr/share/man/man3/udev_monitor_new_from_netlink.3
/usr/share/man/man3/udev_monitor_receive_device.3
/usr/share/man/man3/udev_monitor_ref.3
/usr/share/man/man3/udev_monitor_set_receive_buffer_size.3
/usr/share/man/man3/udev_monitor_unref.3
/usr/share/man/man3/udev_new.3
/usr/share/man/man3/udev_ref.3
/usr/share/man/man3/udev_unref.3

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libsystemd.so
/usr/lib32/libudev.so
/usr/lib32/pkgconfig/32libsystemd.pc
/usr/lib32/pkgconfig/32libudev.pc
/usr/lib32/pkgconfig/libsystemd.pc
/usr/lib32/pkgconfig/libudev.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/systemd/*

%files extras
%defattr(-,root,root,-)
/usr/bin/systemd-hwdb
/usr/bin/systemd-sysusers
/usr/lib/systemd/system/dbus-org.freedesktop.import1.service
/usr/lib/systemd/system/systemd-importd.service
/usr/lib/systemd/system/systemd-journal-gatewayd.service
/usr/lib/systemd/system/systemd-journal-gatewayd.socket
/usr/lib/systemd/system/systemd-journal-remote.service
/usr/lib/systemd/system/systemd-journal-remote.socket
/usr/lib/systemd/system/systemd-journal-upload.service
/usr/lib/systemd/system/systemd-sysusers.service
/usr/lib/systemd/system/var-lib-machines.mount
/usr/lib/systemd/systemd-import
/usr/lib/systemd/systemd-importd
/usr/lib/systemd/systemd-journal-gatewayd
/usr/lib/systemd/systemd-journal-remote
/usr/lib/systemd/systemd-journal-upload
/usr/lib/systemd/systemd-pull
/usr/lib/udev/cdrom_id
/usr/lib/udev/hwdb.d/20-OUI.hwdb
/usr/lib/udev/hwdb.d/20-acpi-vendor.hwdb
/usr/lib/udev/hwdb.d/20-bluetooth-vendor-product.hwdb
/usr/lib/udev/hwdb.d/20-net-ifname.hwdb
/usr/lib/udev/hwdb.d/20-pci-classes.hwdb
/usr/lib/udev/hwdb.d/20-sdio-classes.hwdb
/usr/lib/udev/hwdb.d/20-sdio-vendor-model.hwdb
/usr/lib/udev/hwdb.d/20-usb-classes.hwdb
/usr/lib/udev/hwdb.d/60-evdev.hwdb
/usr/lib/udev/hwdb.d/60-keyboard.hwdb
/usr/lib/udev/hwdb.d/60-sensor.hwdb
/usr/lib/udev/hwdb.d/70-mouse.hwdb
/usr/lib/udev/hwdb.d/70-pointingstick.hwdb
/usr/lib/udev/hwdb.d/70-touchpad.hwdb
/usr/lib/udev/mtd_probe
/usr/lib/udev/rules.d/60-cdrom_id.rules
/usr/lib/udev/rules.d/60-persistent-alsa.rules
/usr/lib/udev/rules.d/60-persistent-storage-tape.rules
/usr/lib/udev/rules.d/60-persistent-v4l.rules
/usr/lib/udev/rules.d/70-joystick.rules
/usr/lib/udev/rules.d/75-probe_mtd.rules
/usr/lib/udev/rules.d/78-sound-card.rules
/usr/lib/udev/v4l_id
/usr/share/dbus-1/system-services/org.freedesktop.import1.service
/usr/share/dbus-1/system.d/org.freedesktop.import1.conf
/usr/share/man/man5/journal-remote.conf.5
/usr/share/man/man5/journal-remote.conf.d.5
/usr/share/man/man5/journal-upload.conf.5
/usr/share/man/man5/journal-upload.conf.d.5
/usr/share/man/man8/systemd-journal-gatewayd.8
/usr/share/man/man8/systemd-journal-gatewayd.service.8
/usr/share/man/man8/systemd-journal-gatewayd.socket.8
/usr/share/man/man8/systemd-journal-remote.8
/usr/share/man/man8/systemd-journal-remote.service.8
/usr/share/man/man8/systemd-journal-remote.socket.8
/usr/share/man/man8/systemd-journal-upload.8
/usr/share/man/man8/systemd-journal-upload.service.8
/usr/share/polkit-1/actions/org.freedesktop.hostname1.policy
/usr/share/polkit-1/actions/org.freedesktop.import1.policy
/usr/share/polkit-1/actions/org.freedesktop.locale1.policy
/usr/share/polkit-1/actions/org.freedesktop.login1.policy
/usr/share/polkit-1/actions/org.freedesktop.machine1.policy
/usr/share/polkit-1/actions/org.freedesktop.systemd1.policy
/usr/share/polkit-1/actions/org.freedesktop.timedate1.policy
/usr/share/polkit-1/rules.d/systemd-networkd.rules

%files lib
%defattr(-,root,root,-)
/usr/lib/systemd/libsystemd-shared-242.so
/usr/lib64/libnss_myhostname.so.2
/usr/lib64/libnss_mymachines.so.2
/usr/lib64/libnss_resolve.so.2
/usr/lib64/libnss_systemd.so.2
/usr/lib64/libsystemd.so.0
/usr/lib64/libsystemd.so.0.26.0
/usr/lib64/libudev.so.1
/usr/lib64/libudev.so.1.6.14
/usr/lib64/security/pam_systemd.so

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libnss_myhostname.so.2
/usr/lib32/libnss_mymachines.so.2
/usr/lib32/libnss_resolve.so.2
/usr/lib32/libnss_systemd.so.2
/usr/lib32/libsystemd.so.0
/usr/lib32/libsystemd.so.0.26.0
/usr/lib32/libudev.so.1
/usr/lib32/libudev.so.1.6.14
/usr/lib32/security/pam_systemd.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/systemd/LICENSE.GPL2
/usr/share/package-licenses/systemd/LICENSE.LGPL2.1

%files man
%defattr(0644,root,root,0755)
%exclude /usr/share/man/man5/journal-remote.conf.5
%exclude /usr/share/man/man5/journal-remote.conf.d.5
%exclude /usr/share/man/man5/journal-upload.conf.5
%exclude /usr/share/man/man5/journal-upload.conf.d.5
%exclude /usr/share/man/man8/systemd-journal-gatewayd.8
%exclude /usr/share/man/man8/systemd-journal-gatewayd.service.8
%exclude /usr/share/man/man8/systemd-journal-gatewayd.socket.8
%exclude /usr/share/man/man8/systemd-journal-remote.8
%exclude /usr/share/man/man8/systemd-journal-remote.service.8
%exclude /usr/share/man/man8/systemd-journal-remote.socket.8
%exclude /usr/share/man/man8/systemd-journal-upload.8
%exclude /usr/share/man/man8/systemd-journal-upload.service.8
/usr/share/man/man1/bootctl.1
/usr/share/man/man1/busctl.1
/usr/share/man/man1/coredumpctl.1
/usr/share/man/man1/hostnamectl.1
/usr/share/man/man1/init.1
/usr/share/man/man1/journalctl.1
/usr/share/man/man1/localectl.1
/usr/share/man/man1/loginctl.1
/usr/share/man/man1/machinectl.1
/usr/share/man/man1/networkctl.1
/usr/share/man/man1/portablectl.1
/usr/share/man/man1/resolvconf.1
/usr/share/man/man1/resolvectl.1
/usr/share/man/man1/systemctl.1
/usr/share/man/man1/systemd-analyze.1
/usr/share/man/man1/systemd-ask-password.1
/usr/share/man/man1/systemd-cat.1
/usr/share/man/man1/systemd-cgls.1
/usr/share/man/man1/systemd-cgtop.1
/usr/share/man/man1/systemd-delta.1
/usr/share/man/man1/systemd-detect-virt.1
/usr/share/man/man1/systemd-escape.1
/usr/share/man/man1/systemd-firstboot.1
/usr/share/man/man1/systemd-firstboot.service.1
/usr/share/man/man1/systemd-id128.1
/usr/share/man/man1/systemd-inhibit.1
/usr/share/man/man1/systemd-machine-id-setup.1
/usr/share/man/man1/systemd-mount.1
/usr/share/man/man1/systemd-notify.1
/usr/share/man/man1/systemd-nspawn.1
/usr/share/man/man1/systemd-path.1
/usr/share/man/man1/systemd-run.1
/usr/share/man/man1/systemd-socket-activate.1
/usr/share/man/man1/systemd-tty-ask-password-agent.1
/usr/share/man/man1/systemd-umount.1
/usr/share/man/man1/systemd.1
/usr/share/man/man1/timedatectl.1
/usr/share/man/man5/binfmt.d.5
/usr/share/man/man5/coredump.conf.5
/usr/share/man/man5/coredump.conf.d.5
/usr/share/man/man5/crypttab.5
/usr/share/man/man5/dnssec-trust-anchors.d.5
/usr/share/man/man5/environment.d.5
/usr/share/man/man5/hostname.5
/usr/share/man/man5/journald.conf.5
/usr/share/man/man5/journald.conf.d.5
/usr/share/man/man5/loader.conf.5
/usr/share/man/man5/locale.conf.5
/usr/share/man/man5/localtime.5
/usr/share/man/man5/logind.conf.5
/usr/share/man/man5/logind.conf.d.5
/usr/share/man/man5/machine-id.5
/usr/share/man/man5/machine-info.5
/usr/share/man/man5/modules-load.d.5
/usr/share/man/man5/networkd.conf.5
/usr/share/man/man5/networkd.conf.d.5
/usr/share/man/man5/os-release.5
/usr/share/man/man5/resolved.conf.5
/usr/share/man/man5/resolved.conf.d.5
/usr/share/man/man5/sleep.conf.d.5
/usr/share/man/man5/sysctl.d.5
/usr/share/man/man5/system.conf.d.5
/usr/share/man/man5/systemd-sleep.conf.5
/usr/share/man/man5/systemd-system.conf.5
/usr/share/man/man5/systemd-user.conf.5
/usr/share/man/man5/systemd.automount.5
/usr/share/man/man5/systemd.device.5
/usr/share/man/man5/systemd.dnssd.5
/usr/share/man/man5/systemd.exec.5
/usr/share/man/man5/systemd.kill.5
/usr/share/man/man5/systemd.link.5
/usr/share/man/man5/systemd.mount.5
/usr/share/man/man5/systemd.negative.5
/usr/share/man/man5/systemd.netdev.5
/usr/share/man/man5/systemd.network.5
/usr/share/man/man5/systemd.nspawn.5
/usr/share/man/man5/systemd.path.5
/usr/share/man/man5/systemd.positive.5
/usr/share/man/man5/systemd.preset.5
/usr/share/man/man5/systemd.resource-control.5
/usr/share/man/man5/systemd.scope.5
/usr/share/man/man5/systemd.service.5
/usr/share/man/man5/systemd.slice.5
/usr/share/man/man5/systemd.socket.5
/usr/share/man/man5/systemd.swap.5
/usr/share/man/man5/systemd.target.5
/usr/share/man/man5/systemd.timer.5
/usr/share/man/man5/systemd.unit.5
/usr/share/man/man5/sysusers.d.5
/usr/share/man/man5/timesyncd.conf.5
/usr/share/man/man5/timesyncd.conf.d.5
/usr/share/man/man5/tmpfiles.d.5
/usr/share/man/man5/udev.conf.5
/usr/share/man/man5/user-runtime-dir@.service.5
/usr/share/man/man5/user.conf.d.5
/usr/share/man/man5/user@.service.5
/usr/share/man/man5/vconsole.conf.5
/usr/share/man/man7/bootup.7
/usr/share/man/man7/daemon.7
/usr/share/man/man7/file-hierarchy.7
/usr/share/man/man7/hwdb.7
/usr/share/man/man7/kernel-command-line.7
/usr/share/man/man7/sd-boot.7
/usr/share/man/man7/systemd-boot.7
/usr/share/man/man7/systemd.environment-generator.7
/usr/share/man/man7/systemd.generator.7
/usr/share/man/man7/systemd.journal-fields.7
/usr/share/man/man7/systemd.offline-updates.7
/usr/share/man/man7/systemd.special.7
/usr/share/man/man7/systemd.syntax.7
/usr/share/man/man7/systemd.time.7
/usr/share/man/man7/udev.7
/usr/share/man/man8/30-systemd-environment-d-generator.8
/usr/share/man/man8/halt.8
/usr/share/man/man8/kernel-install.8
/usr/share/man/man8/libnss_myhostname.so.2.8
/usr/share/man/man8/libnss_mymachines.so.2.8
/usr/share/man/man8/libnss_resolve.so.2.8
/usr/share/man/man8/libnss_systemd.so.2.8
/usr/share/man/man8/nss-myhostname.8
/usr/share/man/man8/nss-mymachines.8
/usr/share/man/man8/nss-resolve.8
/usr/share/man/man8/nss-systemd.8
/usr/share/man/man8/pam_systemd.8
/usr/share/man/man8/poweroff.8
/usr/share/man/man8/reboot.8
/usr/share/man/man8/runlevel.8
/usr/share/man/man8/shutdown.8
/usr/share/man/man8/systemd-ask-password-console.path.8
/usr/share/man/man8/systemd-ask-password-console.service.8
/usr/share/man/man8/systemd-ask-password-wall.path.8
/usr/share/man/man8/systemd-ask-password-wall.service.8
/usr/share/man/man8/systemd-backlight.8
/usr/share/man/man8/systemd-backlight@.service.8
/usr/share/man/man8/systemd-binfmt.8
/usr/share/man/man8/systemd-binfmt.service.8
/usr/share/man/man8/systemd-bless-boot-generator.8
/usr/share/man/man8/systemd-bless-boot.service.8
/usr/share/man/man8/systemd-boot-check-no-failures.service.8
/usr/share/man/man8/systemd-coredump.8
/usr/share/man/man8/systemd-coredump.socket.8
/usr/share/man/man8/systemd-coredump@.service.8
/usr/share/man/man8/systemd-cryptsetup-generator.8
/usr/share/man/man8/systemd-cryptsetup.8
/usr/share/man/man8/systemd-cryptsetup@.service.8
/usr/share/man/man8/systemd-debug-generator.8
/usr/share/man/man8/systemd-environment-d-generator.8
/usr/share/man/man8/systemd-fsck-root.service.8
/usr/share/man/man8/systemd-fsck.8
/usr/share/man/man8/systemd-fsck@.service.8
/usr/share/man/man8/systemd-fstab-generator.8
/usr/share/man/man8/systemd-getty-generator.8
/usr/share/man/man8/systemd-gpt-auto-generator.8
/usr/share/man/man8/systemd-growfs.8
/usr/share/man/man8/systemd-growfs@.service.8
/usr/share/man/man8/systemd-halt.service.8
/usr/share/man/man8/systemd-hibernate-resume-generator.8
/usr/share/man/man8/systemd-hibernate-resume.8
/usr/share/man/man8/systemd-hibernate-resume@.service.8
/usr/share/man/man8/systemd-hibernate.service.8
/usr/share/man/man8/systemd-hostnamed.8
/usr/share/man/man8/systemd-hostnamed.service.8
/usr/share/man/man8/systemd-hwdb.8
/usr/share/man/man8/systemd-hybrid-sleep.service.8
/usr/share/man/man8/systemd-importd.8
/usr/share/man/man8/systemd-importd.service.8
/usr/share/man/man8/systemd-initctl.8
/usr/share/man/man8/systemd-initctl.service.8
/usr/share/man/man8/systemd-initctl.socket.8
/usr/share/man/man8/systemd-journald-audit.socket.8
/usr/share/man/man8/systemd-journald-dev-log.socket.8
/usr/share/man/man8/systemd-journald.8
/usr/share/man/man8/systemd-journald.service.8
/usr/share/man/man8/systemd-journald.socket.8
/usr/share/man/man8/systemd-kexec.service.8
/usr/share/man/man8/systemd-localed.8
/usr/share/man/man8/systemd-localed.service.8
/usr/share/man/man8/systemd-logind.8
/usr/share/man/man8/systemd-logind.service.8
/usr/share/man/man8/systemd-machine-id-commit.service.8
/usr/share/man/man8/systemd-machined.8
/usr/share/man/man8/systemd-machined.service.8
/usr/share/man/man8/systemd-makefs.8
/usr/share/man/man8/systemd-makefs@.service.8
/usr/share/man/man8/systemd-makeswap@.service.8
/usr/share/man/man8/systemd-modules-load.8
/usr/share/man/man8/systemd-modules-load.service.8
/usr/share/man/man8/systemd-networkd-wait-online.8
/usr/share/man/man8/systemd-networkd-wait-online.service.8
/usr/share/man/man8/systemd-networkd.8
/usr/share/man/man8/systemd-networkd.service.8
/usr/share/man/man8/systemd-portabled.8
/usr/share/man/man8/systemd-portabled.service.8
/usr/share/man/man8/systemd-poweroff.service.8
/usr/share/man/man8/systemd-quotacheck.8
/usr/share/man/man8/systemd-quotacheck.service.8
/usr/share/man/man8/systemd-random-seed.8
/usr/share/man/man8/systemd-random-seed.service.8
/usr/share/man/man8/systemd-rc-local-generator.8
/usr/share/man/man8/systemd-reboot.service.8
/usr/share/man/man8/systemd-remount-fs.8
/usr/share/man/man8/systemd-remount-fs.service.8
/usr/share/man/man8/systemd-resolved.8
/usr/share/man/man8/systemd-resolved.service.8
/usr/share/man/man8/systemd-rfkill.8
/usr/share/man/man8/systemd-rfkill.service.8
/usr/share/man/man8/systemd-rfkill.socket.8
/usr/share/man/man8/systemd-run-generator.8
/usr/share/man/man8/systemd-shutdown.8
/usr/share/man/man8/systemd-sleep.8
/usr/share/man/man8/systemd-socket-proxyd.8
/usr/share/man/man8/systemd-suspend-then-hibernate.service.8
/usr/share/man/man8/systemd-suspend.service.8
/usr/share/man/man8/systemd-sysctl.8
/usr/share/man/man8/systemd-sysctl.service.8
/usr/share/man/man8/systemd-system-update-generator.8
/usr/share/man/man8/systemd-sysusers.8
/usr/share/man/man8/systemd-sysusers.service.8
/usr/share/man/man8/systemd-time-wait-sync.8
/usr/share/man/man8/systemd-time-wait-sync.service.8
/usr/share/man/man8/systemd-timedated.8
/usr/share/man/man8/systemd-timedated.service.8
/usr/share/man/man8/systemd-timesyncd.8
/usr/share/man/man8/systemd-timesyncd.service.8
/usr/share/man/man8/systemd-tmpfiles-clean.service.8
/usr/share/man/man8/systemd-tmpfiles-clean.timer.8
/usr/share/man/man8/systemd-tmpfiles-setup-dev.service.8
/usr/share/man/man8/systemd-tmpfiles-setup.service.8
/usr/share/man/man8/systemd-tmpfiles.8
/usr/share/man/man8/systemd-udevd-control.socket.8
/usr/share/man/man8/systemd-udevd-kernel.socket.8
/usr/share/man/man8/systemd-udevd.8
/usr/share/man/man8/systemd-udevd.service.8
/usr/share/man/man8/systemd-update-done.8
/usr/share/man/man8/systemd-update-done.service.8
/usr/share/man/man8/systemd-update-utmp-runlevel.service.8
/usr/share/man/man8/systemd-update-utmp.8
/usr/share/man/man8/systemd-update-utmp.service.8
/usr/share/man/man8/systemd-user-sessions.8
/usr/share/man/man8/systemd-user-sessions.service.8
/usr/share/man/man8/systemd-vconsole-setup.8
/usr/share/man/man8/systemd-vconsole-setup.service.8
/usr/share/man/man8/systemd-veritysetup-generator.8
/usr/share/man/man8/systemd-veritysetup.8
/usr/share/man/man8/systemd-veritysetup@.service.8
/usr/share/man/man8/systemd-volatile-root.8
/usr/share/man/man8/systemd-volatile-root.service.8
/usr/share/man/man8/telinit.8
/usr/share/man/man8/udevadm.8

%files services
%defattr(-,root,root,-)
%exclude /usr/lib/systemd/system/dbus-org.freedesktop.import1.service
%exclude /usr/lib/systemd/system/ldconfig.service
%exclude /usr/lib/systemd/system/local-fs.target.wants/systemd-remount-fs.service
%exclude /usr/lib/systemd/system/local-fs.target.wants/tmp.mount
%exclude /usr/lib/systemd/system/machines.target.wants/var-lib-machines.mount
%exclude /usr/lib/systemd/system/multi-user.target.wants/getty.target
%exclude /usr/lib/systemd/system/multi-user.target.wants/remote-fs.target
%exclude /usr/lib/systemd/system/multi-user.target.wants/systemd-ask-password-wall.path
%exclude /usr/lib/systemd/system/multi-user.target.wants/systemd-logind.service
%exclude /usr/lib/systemd/system/multi-user.target.wants/systemd-networkd.service
%exclude /usr/lib/systemd/system/multi-user.target.wants/systemd-resolved.service
%exclude /usr/lib/systemd/system/multi-user.target.wants/systemd-user-sessions.service
%exclude /usr/lib/systemd/system/network-online.target.wants/systemd-networkd-wait-online.service
%exclude /usr/lib/systemd/system/remote-fs.target.wants/var-lib-machines.mount
%exclude /usr/lib/systemd/system/sockets.target.wants/systemd-coredump.socket
%exclude /usr/lib/systemd/system/sockets.target.wants/systemd-initctl.socket
%exclude /usr/lib/systemd/system/sockets.target.wants/systemd-journald-dev-log.socket
%exclude /usr/lib/systemd/system/sockets.target.wants/systemd-journald.socket
%exclude /usr/lib/systemd/system/sockets.target.wants/systemd-networkd.socket
%exclude /usr/lib/systemd/system/sockets.target.wants/systemd-udevd-control.socket
%exclude /usr/lib/systemd/system/sockets.target.wants/systemd-udevd-kernel.socket
%exclude /usr/lib/systemd/system/sysinit.target.wants/cryptsetup.target
%exclude /usr/lib/systemd/system/sysinit.target.wants/kmod-static-nodes.service
%exclude /usr/lib/systemd/system/sysinit.target.wants/proc-sys-fs-binfmt_misc.automount
%exclude /usr/lib/systemd/system/sysinit.target.wants/systemd-ask-password-console.path
%exclude /usr/lib/systemd/system/sysinit.target.wants/systemd-binfmt.service
%exclude /usr/lib/systemd/system/sysinit.target.wants/systemd-journal-flush-msft.service
%exclude /usr/lib/systemd/system/sysinit.target.wants/systemd-journal-flush.service
%exclude /usr/lib/systemd/system/sysinit.target.wants/systemd-journald.service
%exclude /usr/lib/systemd/system/sysinit.target.wants/systemd-machine-id-commit.service
%exclude /usr/lib/systemd/system/sysinit.target.wants/systemd-modules-load.service
%exclude /usr/lib/systemd/system/sysinit.target.wants/systemd-random-seed.service
%exclude /usr/lib/systemd/system/sysinit.target.wants/systemd-sysctl.service
%exclude /usr/lib/systemd/system/sysinit.target.wants/systemd-timesyncd.service
%exclude /usr/lib/systemd/system/sysinit.target.wants/systemd-tmpfiles-setup.service
%exclude /usr/lib/systemd/system/sysinit.target.wants/systemd-udev-trigger.service
%exclude /usr/lib/systemd/system/sysinit.target.wants/systemd-udevd.service
%exclude /usr/lib/systemd/system/sysinit.target.wants/systemd-update-utmp.service
%exclude /usr/lib/systemd/system/system-update-cleanup.service
%exclude /usr/lib/systemd/system/system-update.target
%exclude /usr/lib/systemd/system/systemd-firstboot.service
%exclude /usr/lib/systemd/system/systemd-hwdb-update.service
%exclude /usr/lib/systemd/system/systemd-importd.service
%exclude /usr/lib/systemd/system/systemd-journal-catalog-update.service
%exclude /usr/lib/systemd/system/systemd-journal-gatewayd.service
%exclude /usr/lib/systemd/system/systemd-journal-gatewayd.socket
%exclude /usr/lib/systemd/system/systemd-journal-remote.service
%exclude /usr/lib/systemd/system/systemd-journal-remote.socket
%exclude /usr/lib/systemd/system/systemd-journal-upload.service
%exclude /usr/lib/systemd/system/systemd-sysusers.service
%exclude /usr/lib/systemd/system/systemd-tmpfiles-setup-dev.service
%exclude /usr/lib/systemd/system/systemd-update-done.service
%exclude /usr/lib/systemd/system/timers.target.wants/systemd-tmpfiles-clean.timer
%exclude /usr/lib/systemd/system/var-lib-machines.mount
/usr/lib/systemd/system/autovt@.service
/usr/lib/systemd/system/basic.target
/usr/lib/systemd/system/bluetooth.target
/usr/lib/systemd/system/boot-complete.target
/usr/lib/systemd/system/console-getty.service
/usr/lib/systemd/system/container-getty@.service
/usr/lib/systemd/system/cryptsetup-pre.target
/usr/lib/systemd/system/cryptsetup.target
/usr/lib/systemd/system/ctrl-alt-del.target
/usr/lib/systemd/system/dbus-org.freedesktop.hostname1.service
/usr/lib/systemd/system/dbus-org.freedesktop.locale1.service
/usr/lib/systemd/system/dbus-org.freedesktop.login1.service
/usr/lib/systemd/system/dbus-org.freedesktop.machine1.service
/usr/lib/systemd/system/dbus-org.freedesktop.network1.service
/usr/lib/systemd/system/dbus-org.freedesktop.portable1.service
/usr/lib/systemd/system/dbus-org.freedesktop.resolve1.service
/usr/lib/systemd/system/dbus-org.freedesktop.timedate1.service
/usr/lib/systemd/system/debug-shell.service
/usr/lib/systemd/system/default.target
/usr/lib/systemd/system/emergency.service
/usr/lib/systemd/system/emergency.target
/usr/lib/systemd/system/exit.target
/usr/lib/systemd/system/final.target
/usr/lib/systemd/system/getty-pre.target
/usr/lib/systemd/system/getty.target
/usr/lib/systemd/system/getty@.service
/usr/lib/systemd/system/graphical.target
/usr/lib/systemd/system/halt.target
/usr/lib/systemd/system/hibernate.target
/usr/lib/systemd/system/hybrid-sleep.target
/usr/lib/systemd/system/initrd-cleanup.service
/usr/lib/systemd/system/initrd-fs.target
/usr/lib/systemd/system/initrd-parse-etc.service
/usr/lib/systemd/system/initrd-root-device.target
/usr/lib/systemd/system/initrd-root-fs.target
/usr/lib/systemd/system/initrd-switch-root.service
/usr/lib/systemd/system/initrd-switch-root.target
/usr/lib/systemd/system/initrd-udevadm-cleanup-db.service
/usr/lib/systemd/system/initrd.target
/usr/lib/systemd/system/kexec.target
/usr/lib/systemd/system/kmod-static-nodes.service
/usr/lib/systemd/system/local-fs-pre.target
/usr/lib/systemd/system/local-fs.target
/usr/lib/systemd/system/machine.slice
/usr/lib/systemd/system/machines.target
/usr/lib/systemd/system/multi-user.target
/usr/lib/systemd/system/network-online.target
/usr/lib/systemd/system/network-pre.target
/usr/lib/systemd/system/network.target
/usr/lib/systemd/system/nss-lookup.target
/usr/lib/systemd/system/nss-user-lookup.target
/usr/lib/systemd/system/paths.target
/usr/lib/systemd/system/poweroff.target
/usr/lib/systemd/system/printer.target
/usr/lib/systemd/system/proc-sys-fs-binfmt_misc.automount
/usr/lib/systemd/system/proc-sys-fs-binfmt_misc.mount
/usr/lib/systemd/system/quotaon.service
/usr/lib/systemd/system/reboot.target
/usr/lib/systemd/system/remote-cryptsetup.target
/usr/lib/systemd/system/remote-fs-pre.target
/usr/lib/systemd/system/remote-fs.target
/usr/lib/systemd/system/rescue.service
/usr/lib/systemd/system/rescue.target
/usr/lib/systemd/system/rpcbind.target
/usr/lib/systemd/system/runlevel0.target
/usr/lib/systemd/system/runlevel1.target
/usr/lib/systemd/system/runlevel2.target
/usr/lib/systemd/system/runlevel3.target
/usr/lib/systemd/system/runlevel4.target
/usr/lib/systemd/system/runlevel5.target
/usr/lib/systemd/system/runlevel6.target
/usr/lib/systemd/system/serial-getty@.service
/usr/lib/systemd/system/shutdown.target
/usr/lib/systemd/system/sigpwr.target
/usr/lib/systemd/system/sleep.target
/usr/lib/systemd/system/slices.target
/usr/lib/systemd/system/smartcard.target
/usr/lib/systemd/system/sockets.target
/usr/lib/systemd/system/sound.target
/usr/lib/systemd/system/suspend-then-hibernate.target
/usr/lib/systemd/system/suspend.target
/usr/lib/systemd/system/swap.target
/usr/lib/systemd/system/sysinit.target
/usr/lib/systemd/system/syslog.socket
/usr/lib/systemd/system/system-update-pre.target
/usr/lib/systemd/system/systemd-ask-password-console.path
/usr/lib/systemd/system/systemd-ask-password-console.service
/usr/lib/systemd/system/systemd-ask-password-wall.path
/usr/lib/systemd/system/systemd-ask-password-wall.service
/usr/lib/systemd/system/systemd-backlight@.service
/usr/lib/systemd/system/systemd-binfmt.service
/usr/lib/systemd/system/systemd-bless-boot.service
/usr/lib/systemd/system/systemd-boot-check-no-failures.service
/usr/lib/systemd/system/systemd-coredump.socket
/usr/lib/systemd/system/systemd-coredump@.service
/usr/lib/systemd/system/systemd-exit.service
/usr/lib/systemd/system/systemd-fsck-root.service
/usr/lib/systemd/system/systemd-fsck@.service
/usr/lib/systemd/system/systemd-halt.service
/usr/lib/systemd/system/systemd-hibernate-resume@.service
/usr/lib/systemd/system/systemd-hibernate.service
/usr/lib/systemd/system/systemd-hostnamed.service
/usr/lib/systemd/system/systemd-hybrid-sleep.service
/usr/lib/systemd/system/systemd-initctl.service
/usr/lib/systemd/system/systemd-initctl.socket
/usr/lib/systemd/system/systemd-journal-flush-msft.service
/usr/lib/systemd/system/systemd-journal-flush.service
/usr/lib/systemd/system/systemd-journald-audit.socket
/usr/lib/systemd/system/systemd-journald-dev-log.socket
/usr/lib/systemd/system/systemd-journald.service
/usr/lib/systemd/system/systemd-journald.socket
/usr/lib/systemd/system/systemd-kexec.service
/usr/lib/systemd/system/systemd-localed.service
/usr/lib/systemd/system/systemd-logind.service
/usr/lib/systemd/system/systemd-machine-id-commit.service
/usr/lib/systemd/system/systemd-machined.service
/usr/lib/systemd/system/systemd-modules-load.service
/usr/lib/systemd/system/systemd-networkd-wait-online.service
/usr/lib/systemd/system/systemd-networkd.service
/usr/lib/systemd/system/systemd-networkd.socket
/usr/lib/systemd/system/systemd-nspawn@.service
/usr/lib/systemd/system/systemd-portabled.service
/usr/lib/systemd/system/systemd-poweroff.service
/usr/lib/systemd/system/systemd-quotacheck.service
/usr/lib/systemd/system/systemd-random-seed.service
/usr/lib/systemd/system/systemd-reboot.service
/usr/lib/systemd/system/systemd-remount-fs.service
/usr/lib/systemd/system/systemd-resolved.service
/usr/lib/systemd/system/systemd-rfkill.service
/usr/lib/systemd/system/systemd-rfkill.socket
/usr/lib/systemd/system/systemd-suspend-then-hibernate.service
/usr/lib/systemd/system/systemd-suspend.service
/usr/lib/systemd/system/systemd-sysctl.service
/usr/lib/systemd/system/systemd-time-wait-sync.service
/usr/lib/systemd/system/systemd-timedated.service
/usr/lib/systemd/system/systemd-timesyncd.service
/usr/lib/systemd/system/systemd-tmpfiles-clean.service
/usr/lib/systemd/system/systemd-tmpfiles-clean.timer
/usr/lib/systemd/system/systemd-tmpfiles-setup.service
/usr/lib/systemd/system/systemd-udev-settle.service
/usr/lib/systemd/system/systemd-udev-trigger.service
/usr/lib/systemd/system/systemd-udevd-control.socket
/usr/lib/systemd/system/systemd-udevd-kernel.socket
/usr/lib/systemd/system/systemd-udevd.service
/usr/lib/systemd/system/systemd-update-utmp.service
/usr/lib/systemd/system/systemd-user-sessions.service
/usr/lib/systemd/system/systemd-vconsole-setup.service
/usr/lib/systemd/system/systemd-volatile-root.service
/usr/lib/systemd/system/time-set.target
/usr/lib/systemd/system/time-sync.target
/usr/lib/systemd/system/timers.target
/usr/lib/systemd/system/tmp.mount
/usr/lib/systemd/system/umount.target
/usr/lib/systemd/system/user-.slice.d/10-defaults.conf
/usr/lib/systemd/system/user-runtime-dir@.service
/usr/lib/systemd/system/user.slice
/usr/lib/systemd/system/user@.service
/usr/lib/systemd/user/basic.target
/usr/lib/systemd/user/bluetooth.target
/usr/lib/systemd/user/default.target
/usr/lib/systemd/user/exit.target
/usr/lib/systemd/user/graphical-session-pre.target
/usr/lib/systemd/user/graphical-session.target
/usr/lib/systemd/user/paths.target
/usr/lib/systemd/user/printer.target
/usr/lib/systemd/user/shutdown.target
/usr/lib/systemd/user/smartcard.target
/usr/lib/systemd/user/sockets.target
/usr/lib/systemd/user/sound.target
/usr/lib/systemd/user/systemd-exit.service
/usr/lib/systemd/user/systemd-tmpfiles-clean.service
/usr/lib/systemd/user/systemd-tmpfiles-clean.timer
/usr/lib/systemd/user/systemd-tmpfiles-setup.service
/usr/lib/systemd/user/timers.target

%files locales -f systemd.lang
%defattr(-,root,root,-)

